### ISSUE TITLE
Support compressed debug info sections.

### ISSUE THREAD

**Issue by ttsugriy** [eliben/pyelftools#100]
elffile.py currently assumes that all debug related sections are start with .debug* but objcopy --compress-debug-sections renames them by adding 'z' prefix, so instead of .debug_info, the section becomes .zdebug_info.

**Comment by ttsugriy** [comment]
sent a pull request https://github.com/eliben/pyelftools/pull/102

**Comment by eliben** [comment]
Resolved by #102
