### ISSUE TITLE
Bug in interpreter of DW_CFA_remember_state

### ISSUE THREAD

**Issue by francesco-zappa-nardelli** [eliben/pyelftools#103]
Dear all

I believe there is a small bug in the interpreter of DW_CFA_remember_state.  The interpreter pushes the current line on a stack, but, due to sharing, subsequent bytecode instructions can modify the pushed line whenever they modify the current line.

For instance, this FDE entry:

00000088 000000000000001c 0000005c FDE cie=00000030 pc= 0000000000400980.. 00000000004009d1
  DW_CFA_advance_loc: 4 to 0000000000400984
  DW_CFA_def_cfa_offset: 24
  DW_CFA_advance_loc1: 64 to 00000000004009c4
  DW_CFA_remember_state
  DW_CFA_def_cfa_offset: 8
  DW_CFA_advance_loc: 4 to 00000000004009c8
  DW_CFA_restore_state

should generate:

00000060 000000000000001c 00000034 FDE cie=00000030 pc=0000000000400980..00000000004009d1
   LOC           CFA      ra
0000000000400980 rsp+8    c-8
0000000000400984 rsp+24   c-8
00000000004009c4 rsp+8    c-8
00000000004009c8 rsp+24   c-8

 (observe the last +24, due to remembering the line for 400984), while it results in:

00000060 000000000000001c 0000000000000034 FDE cie=00000030 pc=0000000000400980..00000000004009d1
   LOC   CFA      ra
0000000000400980 rsp+8    c-8
0000000000400984 rsp+24   c-8
00000000004009c4 rsp+8    c-8
00000000004009c8 rsp+8    c-8

The final +8 is due due the update to the current line in 4009c4.  

I believe that deep-copying the current line before pushing it on the stack + updating the pc when pulling is a simple fix (patch below).

I cannot submit you a binary to reproduce easily as the FDE entry was obtained by parsing eh_frame info via an eh_frame parser I implemented (that I will eventually contribute to pyelftools) and not by parsing debug_frames.

-francesco

```
Index: pyelftools/elftools/dwarf/callframe.py
===================================================================
--- pyelftools/elftools/dwarf/callframe.py  (original)
+++ pyelftools/elftools/dwarf/callframe.py  (working copy)
@@ -501,9 +501,11 @@
                 else:
                     cur_line.pop(instr.args[0], None)
             elif name == 'DW_CFA_remember_state':
-                line_stack.append(cur_line)
+                line_stack.append(copy.deepcopy(cur_line))
             elif name == 'DW_CFA_restore_state':
+                pc = cur_line['pc'] 
                 cur_line = line_stack.pop()
+                cur_line['pc'] = pc

         # The current line is appended to the table after all instructions
         # have ended, in any case (even if there were no instructions).
```

**Comment by eliben** [comment]
Thanks, and sorry for the delay in responsing. Could you submit a fixing PR?

**Comment by ulysses4ever** [comment]
@eliben [here you are](https://github.com/eliben/pyelftools/pull/174).

**Comment by eliben** [comment]
Now with the fix, it's important to have a test. @francesco-zappa-nardelli pyelftools has some support for eh_frame parsing now so maybe your original test should work?

**Comment by francesco-zappa-nardelli** [comment]
Hi all.  It took me a while to regenerate a binary that exhibits this problem, but here you go.  The relevant x86_64 binary is available from: [https://www.di.ens.fr/~zappa/stuff/reduced](https://www.di.ens.fr/~zappa/stuff/reduced) .   readelf -wF correctly outputs:

```00000088 000000000000001c 0000005c FDE cie=00000030 pc=000000000040048d..0000000000400515
   LOC           CFA      rbx   ra      
000000000040048d rsp+8    u     c-8   
000000000040048e rsp+16   c-16  c-8   
0000000000400507 rsp+8    c-16  c-8   
0000000000400508 rsp+16   c-16  c-8 
```

while pyelftools/readelf misexecutes the remember_state / restore_state instructions of the eh_frame table

```00000088 000000000000001c 0000005c FDE cie=00000030 pc=000000000040048d..0000000000400515
  DW_CFA_advance_loc: 1 to 000000000040048e
  DW_CFA_def_cfa_offset: 16
  DW_CFA_offset: r3 (rbx) at cfa-16
  DW_CFA_advance_loc1: 121 to 0000000000400507
  DW_CFA_remember_state
  DW_CFA_def_cfa_offset: 8
  DW_CFA_advance_loc: 1 to 0000000000400508
  DW_CFA_restore_state
  DW_CFA_nop
  DW_CFA_nop
  DW_CFA_nop
```

generating:

```00000088 000000000000001c 0000005c FDE cie=00000030 pc=000000000040048d..0000000000400515
   LOC           CFA      rbx   ra
000000000040048d rsp+8    u     c-8   
000000000040048e rsp+16   c-16  c-8   
0000000000400507 rsp+8    c-16  c-8   
0000000000400508 rsp+8    c-16  c-8   
```
(observe the rsp+8 instead of rsp+16 in the last line).
