### ISSUE TITLE
High level functionalities

### ISSUE THREAD

**Issue by P1kachu** [eliben/pyelftools#106]
There is no high level functions to play with the DWARF symbols. You need to do everything from the original structures which is not always easy. Is this a personnal choice not to provide any or do you accept some high level pull request to enhance this ? (For example, utils to link structure declarations in code to easily access their member's values)

**Comment by eliben** [comment]
This is from choice. The array of higher-level features for DWARF is huge, and I wanted to limit the scope of pyelftools as foundational infrastructure.

**Comment by P1kachu** [comment]
Okay thank you
