### ISSUE TITLE
CompileUnit: Track DIEs by offset

### ISSUE THREAD

**Issue by JonathonReinhart** [eliben/pyelftools#113]
DIEs refer to one another by their offset in the stream.

For example, a [`DW_TAG_typedef`](http://www.dwarfstd.org/doc/DWARF4.pdf#page=96) DIE will have  "a `DW_AT_type` attribute whose value is a reference to the type named by the typedef."

So to get the actual type of a typedef DIE, I currently use something like this in my monkey-patched `CompileUnit` class:

``` python
import elftools.dwarf.compileunit
class MyCompileUnit(elftools.dwarf.compileunit.CompileUnit):

    def get_DIE_at_offset(self, offset):
        for die in self.iter_DIEs():
            if die.offset == offset:
                return die 
        return None

elftools.dwarf.compileunit.CompileUnit = MyCompileUnit
```

This O(n) lookup is inefficient.

Currently, `CompileUnit` [stores all of the DIEs in a simple list](https://github.com/eliben/pyelftools/blob/60319cbb9d469e8d7c56e8f85dd55294c0ce4f62/elftools/dwarf/compileunit.py#L120).

I propose instead (or also) storing them in a dictionary, using their `offset` as the key. This will be unique for all DIEs, and provide fast lookup via a new function like:

``` python
def _get_DIE_by_offset(self, offset):
    return self._diedict[offset]
```

Since the existing `_get_DIE` could be used by existing code (even though it is "private"), it makes sense to leave the existing infrastructure in place, and maintain this offset-lookup side-by-side.

**Comment by eliben** [comment]
Sure, I don't see why not (PRs welcome :)), but this isn't high priority. Compared to time needed to parse the DWARF, building a dict outside CompileUnit should be trivial (time-wise). It gives you all the DIEs, so if you anticipate frequent lookups you can create the offset->DIE mapping yourself.

**Comment by JonathonReinhart** [comment]
Yes, I do hope to submit a PR, it's just a matter of when.  I opened this issue to a) advertise my thoughts in case there were any conflicts with existing efforts, and b) remind myself what the hell my plan was in the future :smiley:

**Comment by eliben** [comment]
Let me know if you plan to be working on this. Since this is something that may be relatively easy to do outside pyelftools, I'm not super-inclined to add it to the library.

**Comment by georgemorgan** [comment]
This would be substantially helpful for me. I spent a while looking around the source code trying to find this until I discovered I needed to implement it myself.

**Comment by dgvogol** [comment]
How about using a SortedKeyList from sortedcontainers library instead of the simple list? So a quick search can be done easily. Right now, all DIEs are sorted by offset in the _dielist, a binary search is possible.

**Comment by mdmillerii** [comment]
#249 was merged and maintains an array and a map, using bisect of the map to find the entry in the list.

**Comment by JonathonReinhart** [comment]
Taken care of in #249.

**Comment by zorbanaut** [comment]
How can I implement get_DIE_at_offset now to take advantage of #249?

**Comment by mdmillerii** [comment]
Your right in that #249 just cached the parsing but didn't help lookup by external code.   However, #264 provides APIs to access the cache from a CU, from the overall DWARFInfo, or from a DIE attribute.

I hope #264 will be merged soon.
