### ISSUE TITLE
Retrieving relative address of a variable 

### ISSUE THREAD

**Issue by bernardnongpoh** [eliben/pyelftools#116]
Hello There, I am trying to retrieve the relative address of a variable,  is the following offset 
 
|DW_AT_location    :  AttributeValue(name='DW_AT_location', form='DW_FORM_exprloc', value=[145, 100], raw_value=[145, 100], offset=157) relative from EBP register

Thanks

**Comment by eliben** [comment]
I think this was resolved over email

**Comment by gitttt** [comment]
How can I get the location (relative to some register) of a stack variable having

`AttributeValue(name='DW_AT_location', form='DW_FORM_exprloc', ...` ?

The following code does not work with `DW_FORM_exprloc`:

```
location_list = location_lists.get_location_list_at_offset(location_list_offset)
_, second_part = location_list[0].loc_expr
return second_part + dw_at_location_offset
```

Is it correct that the pyelftool function `attribute_has_location_list` does not consider `DW_FORM_exprloc`?

```
def attribute_has_location_list(attr):
    """ Only some attributes can have location list values, if they have the
        required DW_FORM (loclistptr "class" in DWARF spec v3)
    """
    if (attr.name in (  'DW_AT_location', 'DW_AT_string_length',
                        'DW_AT_const_value', 'DW_AT_return_addr',
                        'DW_AT_data_member_location', 'DW_AT_frame_base',
                        'DW_AT_segment', 'DW_AT_static_link',
                        'DW_AT_use_location', 'DW_AT_vtable_elem_location')):
        if attr.form in ('DW_FORM_data4', 'DW_FORM_data8'):
            return True
    return False
```

Do I have to use a DWARF interpreter for the `DW_FORM_exprloc`? Where can I find one?

**Comment by eliben** [comment]
@gitttt it's possible that this form is not supported by pyelftools yet. Feel free to submit a pull request to implement it.

Thanks

**Comment by shabo1984** [comment]
Hi, I am trying to get the relative address of a variable. I see the attributes of a variable something like this.

DIE attributes OrderedDict([('DW_AT_location', AttributeValue(name='DW_AT_location', form='DW_FORM_exprloc', **value=[145, 184, 127], raw_value=[145, 184, 127]**, offset=660)), 

The corresponding dwarfdump output is 

< 2><0x00000293>      DW_TAG_variable
                        DW_AT_location              len 0x0003: 91b87f: **DW_OP_fbreg -72**

What is the **value** attribute in the above output and how do I get the actual relative address from it

Thanks

**Comment by langston-barrett** [comment]
> What is the value attribute in the above output and how do I get the actual relative address from it

The value attribute is an expression in the DWARF expression language, evaluating it yields the address (or value) of the variable. Check out the DWARF standard sections about the expression language: http://dwarfstd.org/Download.php
