### ISSUE TITLE
Error dump of .bss section

### ISSUE THREAD

**Issue by subler** [eliben/pyelftools#119]
When dump `.bss` section by -x(byte) or -p(string), readelf.py will error generate content from other section.

    zhongsiz@dinah:~/work/emittersvn> readelf.py -x .bss reloc.o.old

    Hex dump of section '.bss':
      0x00000000 0066756e 63315f5f 46760066 756e6332 .func1__Fv.func2
      0x00000010 5f5f4676                            __Fv

In object file (gcc compile with -c), `.bss` section have no content, the offset is conjoint with next section

    [Nr] Name              Type             Address           Offset
          Size              EntSize          Flags  Link  Info  Align
    ...
    [ 4] .bss              NOBITS           0000000000000000  00000130
          0000000000000014  0000000000000000  WA       0     0     4
    [ 5] .rodata           PROGBITS         0000000000000000  00000130
          0000000000000000  0000000000000000   A       0     0     1

I think the bug results from error consider the size when dump section content.

**Comment by eliben** [comment]
Is this a specific object file for which the problem manifests? Or is this for any object file?

**Comment by subler** [comment]
@eliben it's for some special case, minimize as follow.:

    static int c;
    void func1()
    {
        if (c == 10)
            goto LL;
    LL:
        c = 11;
    }

dump result
   
    Hex dump of section '.bss':
    0x00000000 00474343                            .GCC

**Comment by eliben** [comment]
@subler can you provide the compilation command to produce the object file from this code?

**Comment by subler** [comment]
@eliben Compile with gcc4.9.3 on linux `gcc -c case.cpp`.

**Comment by eliben** [comment]
I believe this is fixed now. Thanks for the report
