### ISSUE TITLE
Compute Elf File Size

### ISSUE THREAD

**Issue by robomotic** [eliben/pyelftools#12]
Hello Eli!
I love your project and because I need to be able to extract elf files from a stream of data I want to be able to calculate the file size by parsing the headers+program sections.
I had in mind two ways to calculate the effective file size but none work so far.
The first approach is sum up: header + program headers + section headers+ program sections.
The second approach is sum up: last program section + file size + header table size.
I have tried the function against your elf samples and they underestimate the file size.
Could you tell me what I am missing in my calculation?

```
def compute_file_size(self):
    self._emitline('File size:')
    header_size=self.elffile.header['e_ehsize'];
    table_program_size=self.elffile.header['e_phentsize']*self.elffile.header['e_phnum'];
    table_headers_size=self.elffile.header['e_shnum']*self.elffile.header['e_shentsize'];

    if self.elffile.num_segments() == 0:
        self._emitline('There are no program headers in this file.')
        return
    program_size=0
    #get the last segmment
    last_offset=0
    last_size=0
    for segment in self.elffile.iter_segments():
        program_size+=segment['p_filesz']
        if segment['p_offset']>last_offset:
            last_offset=segment['p_offset']
            last_size=segment['p_filesz']
    print "Last Offset ", self._format_hex(segment['p_offset'], fieldsize=6)
    print "Last Size", self._format_hex(segment['p_filesz'], fieldsize=5)
    total_size=header_size+table_program_size+table_headers_size+program_size
    print "Total Size via segments %d bytes \n"% (total_size)
    print "Total Size via offset   %d bytes \n"% (last_offset+last_size+table_headers_size)
```

**Comment by probonopd** [comment]
I have the same issue. How do I calculate the length of an ELF on disk?
`photorec` seems to recover ELFs but it simply assumes the length to be as long as until the start of the next file it can identify, which is clearly wrong.
