### ISSUE TITLE
fail to import elffile on windows (+patch)

### ISSUE THREAD

**Issue by screwer** [eliben/pyelftools#123]
Due to missing 'getpagesize' field in 'resource':

> D:\GITREP\python\pyelftools\scripts>D:\GITREP\python\pyelftools\scripts\readelf.py
> Traceback (most recent call last):
>   File "D:\GITREP\python\pyelftools\scripts\readelf.py", line 23, in <module>
>     from elftools.elf.elffile import ELFFile
>   File "C:\tools\Python27\lib\site-packages\elftools\elf\elffile.py", line 15, in <module>
>     if not resource.getpagesize:
> AttributeError: 'module' object has no attribute 'getpagesize'

There is simple patch:
```
try:
    import resource
++    if "getpagesize" not in dir(resource):
++        raise ImportError
    PAGESIZE = resource.getpagesize()
except ImportError:
    # Windows system
    import mmap
    PAGESIZE = mmap.PAGESIZE
```

**Comment by eliben** [comment]
Would you mind submitting a pull request? This way I can just merge it, Travis will run tests on it, etc.
