### ISSUE TITLE
how to decode the struct definition 

### ISSUE THREAD

**Issue by slowpy** [eliben/pyelftools#125]
Dose call iter_DIEs() make sense

what filter should be used? DW_TAG_structure_type ,DW_AT_specification , or other ect

Oh, use iter_DIEs, I got things like:

DW_TAG_structure_type
OrderedDict([('DW_AT_name', AttributeValue(name='DW_AT_name', form='DW_FORM_string', value='sss', raw_value='sss', offset=129))

**Comment by eliben** [comment]
Please update the issue with more information

**Comment by slowpy** [comment]
a function like fss, it’s parameter sp is a struct. how can I got sss (sp type )’definition
the code like:
struct sss{
	int iii;
	char ccc;
};
void fss(struct sss *sp){
}
void fnull(){}

**Comment by slowpy** [comment]
I got there's a type "type StructType" in golang. I did not find in elftools

https://golang.org/pkg/debug/dwarf/

**Comment by eliben** [comment]
pyelftools does not decode `DW_AT_type` for you -- it's just a low level API to extract the relevant DIEs. I could accept a PR for an example that does something simple.
