### ISSUE TITLE
Please DO NOT use any section info when parsing segment!

### ISSUE THREAD

**Issue by douniwan5788** [eliben/pyelftools#130]
I want to parse some "striped" dynamic library which has malformed section info,so I want to parse it in linker view using only segment info.BUT class [DynamicSegment](https://github.com/eliben/pyelftools/blob/60319cbb9d469e8d7c56e8f85dd55294c0ce4f62/elftools/elf/dynamic.py#L184) initializes with the original malformed sections, it just makes no sense...

**Comment by nneonneo** [comment]
It looks like the easiest solution would be simply to pass `None` as the `stringtable` and let `Dynamic` fill it out using `DT_STRTAB`. This really should be the correct solution, rather than trying to get `sh_link` from a potentially unreliable section table.

**Comment by mdmillerii** [comment]
Does 430e3a550f9c7b64b4b3630d319442aa79e3db19 address this?
