### ISSUE TITLE
7zip header errors

### ISSUE THREAD

**Issue by SkyLeach** [eliben/pyelftools#142]
` 	/auto/swc-iabu/TES/Hotfix/Cisco_Workload_Automation_6.3_Release.zip ` and numerous other zip files contain invalid header sections which cause an error return even though the zip is extracted. 

This causes the imageunbundler to return an error code and exit prematurely without scanning the output.  There is a simple fix for this.

**Comment by eliben** [comment]
I don't think you opened this issue in the right project

**Comment by SkyLeach** [comment]
oops
