### ISSUE TITLE
Extract exported symbols like nm

### ISSUE THREAD

**Issue by CaledoniaProject** [eliben/pyelftools#144]
I'm trying to find an example here, that can extract the exported symbols of a SO file

https://github.com/eliben/pyelftools/tree/master/examples

Can you kindly add one?

**Comment by eliben** [comment]
The `readelf` clone in `scripts/readelf.py` can dump a symbol table, just like `readelf` with the `-s` flag. Try:

`$ python scripts/readelf.py -s test/testfiles_for_readelf/penalty_32_gcc.o.elf
`
