### ISSUE TITLE
ELF bytes to function pointer

### ISSUE THREAD

**Issue by jpivarski** [eliben/pyelftools#156]
This isn't a bug-report per say, but given that you said, "If you find any part of the documentation lacking...", I'll ask my question here.

I would like to use pyelftools to find a function pointer in an ELF bytes string. Numba can produce compiled functions, giving me a pointer to the function in local memory and a (hopefully) portable version of the function as an ELF. I want to send the function to a remote site and run it there (on a secured network with known hardware!), so I want to load the ELF as a string and get a new function pointer in the new process.

For example,
```python
>>> import numba
>>> @numba.cfunc("f8(f8)", nopython=True)
... def simple_function(x):
...   return x + 3.14
```

It's made to be called locally:
```python
>>> simple_function.address
140625355096096L
>>> import ctypes
>>> f = ctypes.CFUNCTYPE(ctypes.c_double, ctypes.c_double)(simple_function.address)
>>> f(12)
15.14
```

But we can also get the ELF:
```python
>>> elfbytes = simple_function._library._compiled_object
>>> import numpy
>>> numpy.frombuffer(elfbytes).view(numpy.uint8)
array([127,  69,  76,  70,   2,   1,   1,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   1,   0,  62,   0,   1,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0, 160,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        64,   0,   0,   0,   0,   0,  64,   0,   7,   0,   1,   0,  72,
       184,   0,   0,   0,   0,   0,   0,   0,   0, 242,  15,  88,   0,
        49, 192, 242,  15,  17,   7, 195, 102, 102,  46,  15,  31, 132,
         0,   0,   0,   0,   0,  72, 184,   0,   0,   0,   0,   0,   0,
         0,   0, 242,  15,  88,   0, 195,   0,  31, 133, 235,  81, 184, <- right there!!!
        30,   9,  64,  31, 133, 235,  81, 184,  30,   9,  64,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  12,   0,   0,   0,
         4,   0, 241, 255,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,   0,
         4,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,  79,   0,   0,   0,  18,   0,   2,   0,
         0,   0,   0,   0,   0,   0,   0,   0,  21,   0,   0,   0,   0,
         0,   0,   0,  73,   0,   0,   0,  18,   0,   2,   0,  32,   0,
         0,   0,   0,   0,   0,   0,  15,   0,   0,   0,   0,   0,   0,
         0,   2,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,
         2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  34,
         0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   2,   0,
         0,   0,   8,   0,   0,   0,   0,   0,   0,   0,   0,  46, 114,
       101, 108,  97,  46, 116, 101, 120, 116,   0, 115, 105, 109, 112,
       108, 101,  95, 102, 117, 110,  99, 116, 105, 111, 110,   0,  46,
       110, 111, 116, 101,  46,  71,  78,  85,  45, 115, 116,  97,  99,
       107,   0,  46, 115, 116, 114, 116,  97,  98,   0,  46, 115, 121,
       109, 116,  97,  98,   0,  46, 114, 111, 100,  97, 116,  97,  46,
        99, 115, 116,  56,   0,  99, 102, 117, 110,  99,  46,  95,  95,
       109,  97, 105, 110,  95,  95,  46, 115, 105, 109, 112, 108, 101,
        95, 102, 117, 110,  99, 116, 105, 111, 110,  36,  49,  46, 102,
       108, 111,  97, 116,  54,  52,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  44,
         0,   0,   0,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  40,   1,   0,
         0,   0,   0,   0,   0, 114,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,   0,
         0,   0,   1,   0,   0,   0,   6,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  64,   0,   0,   0,
         0,   0,   0,   0,  47,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  16,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,
         0,   4,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0, 248,   0,   0,   0,   0,
         0,   0,   0,  48,   0,   0,   0,   0,   0,   0,   0,   6,   0,
         0,   0,   2,   0,   0,   0,   8,   0,   0,   0,   0,   0,   0,
         0,  24,   0,   0,   0,   0,   0,   0,   0,  60,   0,   0,   0,
         1,   0,   0,   0,  18,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 112,   0,   0,   0,   0,   0,
         0,   0,  16,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   8,   0,   0,   0,   0,   0,   0,   0,
         8,   0,   0,   0,   0,   0,   0,   0,  28,   0,   0,   0,   1,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0, 128,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  52,   0,   0,   0,   2,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0, 128,   0,   0,   0,   0,   0,   0,   0,
       120,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   3,
         0,   0,   0,   8,   0,   0,   0,   0,   0,   0,   0,  24,   0,
         0,   0,   0,   0,   0,   0], dtype=uint8)
```

Looking at my local pointer for reference, the first 50 bytes after the function pointer is
```python
>>> numpy.ctypeslib.as_array(ctypes.cast(simple_function.address, ctypes.POINTER(ctypes.c_uint8)), (50,))
array([ 72, 184,   8,  48,  86, 228, 229, 127,   0,   0, 242,  15,  88,
         0, 195,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint8)
```
Only the first three bytes (72, 184, 8) and the (0, 0, 242, 15, 88, 0, 195, 0) section are consistent from run to run, with the 8-byte string coming right before a representation of 3.14 (31, 133, 235, 81, 184, 30, 9, 64). I see this starting on byte 117 in the ELF (labeled "right there").

So it's in there.

On to pyelftools:
```python
>>> from elftools.elf.elffile import ELFFile
>>> from io import BytesIO
>>> elf = ELFFile(BytesIO(elfbytes))
```

The last section has the symbol table:
```python
>>> list(elf.iter_sections())
[<elftools.elf.sections.NullSection object at 0x7fe5db704710>, <elftools.elf.sections.StringTableSection object at 0x7fe5db704690>, <elftools.elf.sections.Section object at 0x7fe5db704610>, <elftools.elf.relocation.RelocationSection object at 0x7fe5db704590>, <elftools.elf.sections.Section object at 0x7fe5db704810>, <elftools.elf.sections.Section object at 0x7fe5db704950>, <elftools.elf.sections.SymbolTableSection object at 0x7fe5db704990>]
```
and it has the expected symbol names:
```python
>>> [x.name for x in list(elf.iter_sections())[-1].iter_symbols()]
[u'', u'simple_function', u'', u'__main__.simple_function$1.float64', u'cfunc.__main__.simple_function$1.float64']
```
The last one ("`cfunc.__main__.simple_function$1.float64`") is the function I want. (I can see that by reading the LLVM in `simple_function._library.get_llvm_str()`.)

I see that these `Symbol` objects have an `entry` dict-like, and some of these are numerical offsets, but how do I get the offset from the beginning of the ELF?

That is, if I load the ELF bytes into a Numpy array, how do I use the information from pyelftools to construct an offset relative to the base address of that array? (In other words, how do I do `dlsym` with pyelftools?)

(This ELF doesn't seem to be compatible with the normal `dlopen`/`dlsym` mechanism: writing to a file and doing `ctypes.cdll.LoadLibrary` results in `OSError: /tmp/dummy.so: only ET_DYN and ET_EXEC can be loaded`.)

**Comment by eliben** [comment]
I'd be surprised if this ELF was loadable, it's likely an object file which isn't linked/relocated. Not sure what you mean by offset from beginning of ELF though? What exactly do you need to do?

**Comment by jpivarski** [comment]
It was my impression that you can execute functions in an ELF file by memory mapping it, finding the bytecode for the function as an offset relative to the base pointer of the memory map, casting that as a function pointer, and then calling the function. In my case, the ELF bytes are already in memory and shouldn't have to touch disk. The hard part, whether the file comes from disk or starts in memory, is finding the function's bytecode within the ELF. I'm hoping that pyelftools can help with that by interpreting the headers for me.

Actually saving my ELF string as a file and loading it with dlopen/dlsym (or ctypes) would be an unsatisfactory but usable solution if it worked, but it doesn't work. You weren't surprised that it didn't work, that there are object files that can't be linked/reloaded.

I know that the information needed to reconstruct the executable function is in this particular ELF file, since it's possible to transport it and reconstruct it with the full Numba/llvmlite/LLVM toolchain: https://stackoverflow.com/a/42198101/1623645

But in principle all of those dependencies shouldn't be required on the remote machines (which don't actually compile anything), since ELF is a widely recognized standard, and the remote machines have the same instruction set as the compiler. I'd like to find out if I can execute this function with only pyelftools and maybe other lightweight dependencies.

**Comment by eliben** [comment]
I think this is mostly a question for the Numba folks then; `pyelftools` will let you extract stuff from an ELF image, but first you'd have to find *what* information to extract, e.g. how to treat the image as executable. I expect there's some matter of runtime relocation required, especially for remote execution. Even if the code is entirely position independent, it may need things like GOT and PLT relocated (these live outside the text section, but there's still some loading work to do).

**Comment by jpivarski** [comment]
Okay, thank you! (I didn't realize there was this much flexibility in the ELF format.) I'll direct my question there.
