### ISSUE TITLE
Add EF_MIPS_PIC to E_FLAGS to readelf.py to match binutils readelf output

### ISSUE THREAD

**Issue by mzpqnxow** [eliben/pyelftools#164]
pyelftools picked up CPIC but not PIC
    
    binutils readelf says:
      Flags:                             0x1007, noreorder, pic, cpic, o32, mips1
    
    pyelftools said (before this change):
      Flags:                             0x1007, noreorder, cpic, o32, mips1
    
    Reproduce with the binary available at:
    
    https://github.com/mzpqnxow/embedded-toolkit/blob/master/prebuilt_static_bins/gdbserver/gdbserver-6.8-mips-i-rtl819x-lexra

I will attach a pull request

**Comment by mzpqnxow** [comment]
#165 has been submitted to address this issue. It is a trivial change

**Comment by eliben** [comment]
Can you please close this and other issues that were addressed by your recent merged PRs? Thanks
