### ISSUE TITLE
Only use os- and processor- specific enum values on the appropriate os and processor

### ISSUE THREAD

**Issue by rhelmot** [eliben/pyelftools#175]
So this is the _actual_ cause that was behind yesterday's issue, though that is probably still a problem.

If you look at how this project tries to load the file linked from this issue https://github.com/angr/cle/issues/103#issuecomment-355405436 it crashes because it thinks the dynamic tag 0x6000000f is `DT_SUNW_FILTER`, and assumes that the corresponding d_val points to a string. However, this is not solaris, and 0x6000000f is not a filter here, so the pointer is not an index into a string table, and so the lookup crashes.

This seems like a very complicated and invasive change, and I don't know anything about the architecture of this project, so I'd appreciate a response other than "patches welcome".

**Comment by eliben** [comment]
I think this is the same issue in #121 and #71, right? 

These issues have some clues about possible solutions, but you're right that it's not trivial. It'd be great if someone found time to finally fix this, though :)

**Comment by eliben** [comment]
In the past days 73716604dcd617f77ea39f20b32189ca6dc395e5 and 5fc2c25d3f3567020eaf17faf09ad074090ab6b3 landed to implement machine detection. I believe this is very similar to what's required here for OS detection

**Comment by eliben** [comment]
Specifically, pyelftools already reads the `EI_OSABI` offset in `e_ident` and has a table of OS/ABI, which can be used to identify such fields.

Could you provide a minimal test file where this problem can be observed?

**Comment by rhelmot** [comment]
Here is a test file. It was provided to me by one of my users and I have no idea how to make it smaller, but the nature of the problem is evident.

[libLLVM.so.gz](https://github.com/eliben/pyelftools/files/1735203/libLLVM.so.gz)

```python
from elftools.elf import elffile                                                                         
                                                                                                         
e = elffile.ELFFile(open('/home/audrey/Downloads/libLLVM.so', 'rb'))                                     
dyn = e.get_section_by_name('.dynamic')                                                                  
soname = [ x.soname for x in list(dyn.iter_tags()) if x.entry.d_tag == 'DT_SONAME']                      
print soname 
```

I've looked over the commits you linked and yes, it's now basically within reach to do the same thing. The problem is... I don't know what sort of values of `EI_OSABI` actually correspond to `DT_SUNW_*` being valid. As far as I can tell that file is totally valid but none of its header values betray a deviation of the norm. My _guess_ is that this is an android library and the correct values should come from [here](http://llvm.org/doxygen/BinaryFormat_2ELF_8h.html), but I have no idea how to detect that.

**Comment by rhelmot** [comment]
Found the relevant code in readelf. https://chromium.googlesource.com/native_client/nacl-binutils/+/upstream/master/binutils/readelf.c#1986

Pull request incoming.
