### ISSUE TITLE
from Construct developer, a note

### ISSUE THREAD

**Issue by arekbulski** [eliben/pyelftools#180]
I am the developer of Construct (a parsing library) since I took over the project 2 years ago. Please refer any other projects that also use this library to this post, or copy it over to them. 

Construct is undergoing heavy changes at the moment, similar to those between 2.5->2.8, including addition of compiler feature (to make it much faster than Kaitai), but also several classes are going to be removed (for a good reason), and also few were added. API will be unstable for about a month.

What you can do:
- All scheduled work is posted as tickets, in [Issues](https://github.com/construct/construct/issues) and also on [Kanban](https://github.com/construct/construct/projects/3) page. If you subscribe (watch repository) then you will have advance notice of any incoming changes. Unfortunately those tickets also include minor work items, so you would get some clutter notifications too. I appologise for that.
- I encourage everyone to browse those tickets, vote for feature requests, but also post objections for planned removal of features, or changes in semantics. Subscribing therefore is recommended.
- You can find what was already changed (at any moment) on [Transition page](https://construct.readthedocs.io/en/latest/transition29.html), which is like a growing changelog. It gets updated whenever something gets added or removed, but since the order is not chronological, new items do not end up on top or bottom of the list.
- You can find currently available classes and semantics on revamped [Core API pages](https://construct.readthedocs.io/en/latest/index.html#api-reference). Those pages are very extensive and always uptodate with the implementation.
- **Feel free, at any point in time, to open a new Issue and ask questions or make complaints** about breakage. At minimum, I can offer advice and possible alternatives. People very often use the classes in ways that were not designed for, like use String classes to process Bytes.
- **Feel free, at any point in time, to open a new Issue and request changes.** If you need a new class, and make a good clear case, I would be more than willing to add it to core library to support your project.
- API should be stable within a month, so either do version pinning and deal with it then, or keep fixing your code at every release (which is ~3 day cycle at the moment).

Close this topic at your discretion.

**Comment by arekbulski** [comment]
Since this project used to depend on 2.5 which is 2 YEARS OUT OF DATE, I imagine it would require some work to bring it up to date. I am willing to help you out with it, but not do the entire work.

**Comment by eliben** [comment]
@arekbulski thanks for the notice. Would it be correct to say that the API has changed significantly from 2.5 to 2.8, meaning that I'll have to rewrite most of my construct-using code?

**Comment by arekbulski** [comment]
Yes, you would need to rewrite all your construct code. The current changes (2.9) will break few things on top of that, but not as many as those in 2.8. 
If you decide to go ahead, feel free to ask questionsat any point if you get stuck on anything.

**Comment by eliben** [comment]
I see.

I'll have to weigh these costs vs. the projected benefits of updating the construct dependency.

**Comment by arekbulski** [comment]
Sorry I wont be able to rewrite it for you. Its not even that I dont have a particular interest in this project, which I dont really, but its just too much code to be rewritten. Your entire repo looks unmaintained. But if you ever need some support, just ask on Issues or Chat.

**Comment by rathann** [comment]
@eliben have you thought about porting pyelftools to the latest construct API?
