### ISSUE TITLE
Q: EM_BLAFKIN vs EM_BLACKFIN

### ISSUE THREAD

**Issue by umlaeute** [eliben/pyelftools#181]
according to the [linux kernel sources](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/elf-em.h) and also to [elftools/elf/enums.py](https://github.com/eliben/pyelftools/blob/master/elftools/elf/enums.py) `EM_BLACKFIN` seems to be the correct spelling, but `ELFFile.header.e_machine` uses `EM_BLAFKIN` instead.

is this a typo? or intentional?

**Comment by eliben** [comment]
It's a typo - will fix. Thanks

**Comment by eliben** [comment]
Wow... embarrassing :-) Fixing for real now, thanks for noticing!

**Comment by vapier** [comment]
i happened to notice the typo today while looking through the code and was going to send a PR.  as the original author, can confirm i should have written `EM_BLACKFIN`.
