### ISSUE TITLE
re-add support for initializing sections with an explicit stream

### ISSUE THREAD

**Issue by rhelmot** [eliben/pyelftools#187]
somewhere between 0.24 and now, the Section constructors had their stream argument removed, and the stream is now grabbed from the reader. I would like the ability to pass in an explicit stream to use besides the one in the reader.

The rationale for this is that when trying to analyze binaries robustly, section data is not actually considered by loaders and is thus a potential wedge for malicious actors to confuse analysis tools by providing misleading data. Instead, we want to use just the program headers (segments) for loading. This means getting the string tables/relocations/etc out of the PT_DYNAMIC segment instead of the section table. However, entries in PT_DYNAMIC provide their addresses in terms of _how they look when actually mapped into an address space_. In our application, we're already constructing the loaded binary into an address space object which supports the python stream interface, so instead of trying to translate the address back into an offset into the binary by checking each of the PT_LOADs again, we used to be able to just provide our copy of the address space directly to a RelocationSection object to be able to read out the relocations, for example.

If you think this is an ok change, I can do it pretty easily.

**Comment by eliben** [comment]
Seems like this was introduced by @pmderodat 

Pierre-Marie, any thoughts? You've specifically removed these for a cleaner support for compressed sections.

@rhelmot are you instantiating `Section` objects manually? If so you could always monkey-patch the `stream` attribute after construction, right?

**Comment by pmderodat** [comment]
Hello,

Sorry for breaking your workflow, @rhelmot! If I remember correctly, I removed the stream argument from section constructors as no code in pyelftools was actually passing a stream that was different from the owning elffile’s, so I thought that was a worthwhile refactoring. I guess this specific part can be reverted without breaking compressed sections support. Please tell me if you need help on that.

PS: @eliben it seems that you merged my multiple commits as a single squashed one (1d7e6945d939197aa722fcd909522c079c69aa3c), so reverting the specific commit that introduced that is not possible anymore. I noticed that at the time of the pull request merge and was a bit surprised: just being curious, why did you do that? (assuming that was on purpose!) @rhelmot maybe you can somehow use https://github.com/eliben/pyelftools/pull/152/commits/6e1b02a9ef0fabc7ea098dc0c7fa24c54a37f776

PS2: @eliben  I’m curious as to how you could do that: when I push to my repos commits coming from PRs after amending them, GitHub does not tag the corresponding PRs as “merged” (they are still open).

Thanks! :-)

**Comment by rhelmot** [comment]
I don't think reverting the commit is necessary - I do like the design of taking the stream from the `reader` when it's available, but I'd like to be able to pass it in when I want to. An optional argument, I guess.

I hadn't thought of monkeypatching it in afterwards! That's a much better hack than what I was doing before.

**Comment by eliben** [comment]
@rhelmot - if monkey patching works for you I'd be inclined to leave it be. The reason is that I see `Section` as an internal class that pyelftools creates and users consume. As @pmderodat no code within pyelftools actually created sections with these streams passed in. You appear to have a unique use case where you are creating `Section` objects on your own. In this case maybe monkey patching is a good enough solution? Let me know if I'm misunderstanding.

@pmderodat squishing multiple commits in PRs is fairly standard on Github. This is why Github now offers a "Squash and merge" option right from the web UI. Folks often have a large number of commits for a single change, working on the change piecemeal, adding tests, fixing bugs, adding docs and so on. Squashing lets us keep a cleaner "one commit per feature" timeline.

**Comment by rhelmot** [comment]
I agree. Monkeypatching can work fine for our case. Thanks!
