### ISSUE TITLE
The v0.24 Release Tarball has Changed

### ISSUE THREAD

**Issue by nategraff-sifive** [eliben/pyelftools#199]
I recently noticed that the [v0.24 release](https://github.com/eliben/pyelftools/releases/tag/v0.24)'s tarball has changed size and checksum.

The v0.24.tar.gz file used to have the following properties:
```
size: 411874
sha512sum: 5169617f9a8446ffc21dfc44ee185a388c8945a0296bdc6752483b0756888dccb10e3ee88e529d101cf31a4595de924b5c95f5459d5ee4448f57c0c4f2c56887
```

The file now has these properties:
```
size: 600985
sha512sum: 5f02018b3c1c6da55c762e4e7a0eb9d5c9d2af542779dbcda231f563eb93565a0b5bd520ab5a4e07b26958122abeea1e76ee8609e4941ac38289adacea50910f
```

The old properties are corroborated by [the Gentoo package manifest](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/pyelftools/Manifest) and by downloading the mirror of the release [from PyPI](https://pypi.org/project/pyelftools/0.24/#files).

I'm filing an issue because this is rather strange and I wanted to find out if the pyelftools maintainers happen to know what might have happened here.

**Comment by eliben** [comment]
I released 0.25 very recently, could it be the reason?
In general I would not count on Github's tarballs as the source of truth here. It's much better to download from PyPI if you need a tarball because that's something I have manually created and tested
