### ISSUE TITLE
Support for .debug_pubtypes and .debug_pubnames?

### ISSUE THREAD

**Issue by rvijayc** [eliben/pyelftools#201]
Hi, 

First of all, this is an incredibly useful tool that I've used to augment and automate many debug tasks. Thanks a lot for developing what I know of as the only Python-only framework for DWARF parsing. 

The one problem that I frequently face is the need to parse the entire ELF on start-up in order to generate indexing information for faster look-up based on three criteria - variable or function name, a type name (struct/enum etc.,), and address. I used to do this by manually walking the entire ELF and storing CU/DIE offsets as a function of names and addresses and types. This is quite time consuming especially when it comes to recursively parsing all the possible type definitions defined in the ELF.

I just recently learned that the DWARF format provides support for .debug_aranges, .debug_pubnames and .debug_pubtypes that pretty eliminates the need for the indexing that I am doing (as they already are the indexes that I need). Unfortunately, while .debug_aranges is supported, the other two (pubnames and pubtypes) aren't yet supported in pyelftools. 

I am wondering if there is a plan to add support for .debug_pubtypes and .debug_pubnames in the near future. If not, there is any other alternative to indexing the entire ELF for faster lookup?

Thanks,
Vijay.

**Comment by eliben** [comment]
I wouldn't object to these capabilities in pyelftools, but I don't have time to work on them myself in the foreseeable future. PRs welcome.

**Comment by rvijayc** [comment]
Thanks Eli. I should be able to add these myself - the parsing method from the DWARF spec is quite simple enough. I need to get permission from my org before I can contribute, but it should be a formality. I'll send patches for review soon.

**Comment by ramwin** [comment]
> Thanks Eli. I should be able to add these myself - the parsing method from the DWARF spec is quite simple enough. I need to get permission from my org before I can contribute, but it should be a formality. I'll send patches for review soon.

Hello, @rvijayc . Is there any progress on this. Recently I'm trying to parse the .debug_types section. It may helps a lot if your org agree to send the patch.
