### ISSUE TITLE
DynamicSegment.iter_symbols() might terminate early

### ISSUE THREAD

**Issue by rupran** [eliben/pyelftools#218]
The following code in DynamicSegment.iter_symbols() might return a too low number of entries for the dynamic symbol table.
 https://github.com/eliben/pyelftools/blob/60319cbb9d469e8d7c56e8f85dd55294c0ce4f62/elftools/elf/dynamic.py#L204-L224

It tries to find the next pointer bigger than the beginning of the symbol table (indicated by the 'DT_SYMTAB' dynamic tag) and uses it as the end of the table. For shared libraries or PIE executables with a load offset of 0, **pointers** to e.g. 'DT_SYMTAB' are something like 0x380 which is in a range where tags like 'DT_STRSZ' or 'DT_RELASZ' have their **value**. However, this code does not make any distinction between value and pointer tags (and it seems there is no generic way to do so anyway) so it might use a size value as the (wrong) end of the symbol table.

Other projects (such as https://github.com/chromium/crashpad) use the information in 'DT_HASH' or 'DT_GNU_HASH' to compute the number of elements in the symbol table as every symbol has a hash associated to it (see the change set introducing this at https://github.com/chromium/crashpad/commit/1f1657d573c789aa36b6022440e34d9ec30d894c)

Should I implement something similar here as well? Additionally, we might also want to provide a DynamicSegment.get_symbol(n) function similar to the regular symbol table.

**Comment by eliben** [comment]
Sure, go for it
