### ISSUE TITLE
Expose public objects in namespace

### ISSUE THREAD

**Issue by binaryflesh** [eliben/pyelftools#222]
In [This use case](https://github.com/trailofbits/manticore/blob/master/manticore/binary/binary.py) in order to import ELFFile, you must either do this or `from elftools.elf import elffile #elffile.ELFFile`. Neither or which are absolute imports to the object in question. This issue highlights the `__init__.py` file not being utilized in a featured use case. Ideally all packages should have an `__all__` variable denoting what `from . import *` imports and take advantage of the namespace, e.g. adding `from .elffile import ELFFile`  to `elftools.elf.__init__.py` would make the following legal: ` from elftools.elf import ELFFile`.

**Comment by eliben** [comment]
Please see my comment on PR #223
