### ISSUE TITLE
errow while building

### ISSUE THREAD

**Issue by AliRazaManzoor** [eliben/pyelftools#224]
debian@debian:~/Desktop/temp/elf_purser/pyelftools-master$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from setuptools import setup
ImportError: No module named setuptools

**Comment by eliben** [comment]
You'll need to have `setuptools` available

**Comment by AliRazaManzoor** [comment]
solved .thanx
