### ISSUE TITLE
Simple example for reading content of static variables

### ISSUE THREAD

**Issue by dkuschmierz** [eliben/pyelftools#227]
Hi, 

i'm new the pyelftools and wanted to ask you guys, if somebody can give an example how to parse the content in an elf-File for a static variables.

For example I have a static uint32_t timestamp = 0x1234; in my code, how can I read out the address and the initial value of that variable?

**Comment by rupran** [comment]
One way to do that would be by fetching the symbol from the symbol table and finding the corresponding file offset via the segment which contains the virtual address of the symbol (see the following script).
Note that this requires the full symbol table, so it will not work on stripped binaries out of the box.

```python3
import struct
import sys
from elftools.elf.elffile import ELFFile

FILE   = 'static_elf'
SYMBOL = 'timestamp'

elf = ELFFile(open(FILE, 'rb'))

# Get the symbol table entry for the respective symbol
symtab = elf.get_section_by_name('.symtab')
sym = symtab.get_symbol_by_name(SYMBOL)[0]
if not symtab or not sym:
    print('Symbol {} not found or no symbol table available!')
    sys.exit(1)

# Find the segment where the symbol is loaded to, as the symbol table points to
# the loaded address, not the offset in the file
file_offset = None
for seg in elf.iter_segments():
    if seg.header['p_type'] != 'PT_LOAD':
        continue
    # If the symbol is inside the range of a LOADed segment, calculate the file
    # offset by subtracting the virtual start address and adding the file offset
    # of the loaded section(s)
    if sym['st_value'] >= seg['p_vaddr'] and sym['st_value'] < seg['p_vaddr'] + seg['p_filesz']:
        file_offset = sym['st_value'] - seg['p_vaddr'] + seg['p_offset']
        break

if not file_offset:
    print('Error getting file offset from ELF data')
    sys.exit(1)

# Forward the file stream to the identified offset
elf.stream.seek(file_offset)
# Read the value as a 4 byte integer and print it
value = struct.unpack('i', elf.stream.read(4))[0]
print('Variable {} at address {} (file offset {}) has value {}'.format(SYMBOL, hex(sym['st_value']), hex(file_offset), hex(value)))
```

For this file:
```C
#include <stdio.h>
#include <stdint.h>

static uint32_t timestamp = 0x1234;

int main(){
	printf("%d\n", timestamp);
}
```
the script gives me this output:
```console
ziegler@dev:~$ python3 static.py 
Variable timestamp at address 0x201010 (file offset 0x1010) has value 0x1234
```

**Comment by ChristianStadelmann** [comment]
Does anyone know how I would get the type of variable `timestamp` in this example?

**Comment by sevaa** [comment]
Take a look at the value of the `DW_AT_type` attribute. It will be a reference to the DIE of the datatype, which in the simplest case will be a `DW_TAG_base_type`. You'd have to follow the reference, potentially to another CU.

The complex case can be, well, very complex. Datatypes in C/C++ can be arbitrarily complex.

Consider using DWARF Explorer. Its original purpose was following DIE references visually.

**Comment by f-zl** [comment]
Great example! I want to add that a static variable in block scope may not appear in the .symtab, but its address can be derived from DW_AT_location in a DW_AT_variable.
