### ISSUE TITLE
Deprecation warning in Python 3.7 on elftools\dwarf\namelut.py

### ISSUE THREAD

**Issue by DraceaAlexandra** [eliben/pyelftools#235]
This is the extended message:
elftools\dwarf\namelut.py:19: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class NameLUT(collections.Mapping):

I've seen that something similar was fixed: https://github.com/eliben/pyelftools/pull/231, but some models failed to be updated also.

**Comment by eliben** [comment]
This seems to be exactly what #231 fixes. Are you saying it's still not fixed? Did you try to use the `master` branch of pyelftools? That fix hasn't made it into a tagged release yet

**Comment by DraceaAlexandra** [comment]
Yes, i took the master branch. The fix in [https://github.com/eliben/pyelftools/pull/231] is addressing only the import from elftools/construct/lib/container.py. The import collections is used also in elftools\dwarf\namelut.py

**Comment by eliben** [comment]
Thanks for clarifying. I will gladly review and merge a PR to fix this

**Comment by woodruffw** [comment]
I can take a stab at this; looks like a relatively small change.

**Comment by eliben** [comment]
@woodruffw sure, go ahead

**Comment by woodruffw** [comment]
My bad, looks like https://github.com/eliben/pyelftools/commit/02100343590b8fd636eea569ce29824844aa5ca6 resolves this.

**Comment by eliben** [comment]
Cool, thanks for checking. 
(I guess I forgot to close the issue, will do now)
