### ISSUE TITLE
is there a way we can know the size of array declared with "extern type array[]" with pyelftools 

### ISSUE THREAD

**Issue by wentongwu** [eliben/pyelftools#238]
Is there a way that we can know the size of array declared with "extern type array[]" in file example.h and defined with "type array[ARRAY_SIZE]" in example.c, and example.c will include example.h. With pyelftools, I analyze all the attributes of array, still can't find the way to calculate the size of array, so is this a bug or I miss someting? Thanks for the help!

Thanks

**Comment by eliben** [comment]
I'm not sure why it would matter to pyelftools where the declaration of the array lives - the preprocessor pastes the header file. See also some SO answers like https://stackoverflow.com/questions/39884428/how-to-derive-the-length-of-a-string-or-an-array-from-dwarf
