### ISSUE TITLE
Customize the ELF and Write it ?

### ISSUE THREAD

**Issue by NikosDelijohn** [eliben/pyelftools#243]
Hi there!

I just wanted to ask,

Is it possible to customize bits and bytes of the ELF file and then produce an altered - change version of it ?

Thanks in advance.

**Comment by eliben** [comment]
Nope, writing ELF back is not a design goal of pyelftools

**Comment by NikosDelijohn** [comment]
Hello again.

Can't i lets say create a function to write a new file with the modified 
field in it using the following loop?

  * for section in elf.iter_sections():
      o new_elf.write(section.data())
