### ISSUE TITLE
How to get the full file path from DW_AT_decl_file

### ISSUE THREAD

**Issue by trevorwhitaker** [eliben/pyelftools#250]
I can't seem to figure this out. I know the DW_AT_decl_file is 1 which I need to lookup in some array but I can't find where that array is. I can get the file name from the line program header but I can't find the full path. I know it exists somewhere in the ELF file since dwarfdump shows the full file path. How do I get this info in pyelftools?

**Comment by woodruffw** [comment]
> I can't seem to figure this out. I know the DW_AT_decl_file is 1 which I need to lookup in some array but I can't find where that array is.

It's in the `.debug_line` section, which you can dump with `llvm-dwarfdump -debug-line` (or maybe GNU `dwarfdump`). 

The resolution process is as follows:

* `DW_AT_decl_file` is an index into the line number information's file table
* Each file table entry contains a null terminated string, which can be either a relative filename or an absolute path
* If the filename is relative, then the directory index in the file table entry can be used to resolve the base directory

For example, here's the file and directory table entries from one of my programs:

```
include_directories[  1] = "/home/foo"
file_names[  1]:
           name: "hello.c"
      dir_index: 1
       mod_time: 0x00000000
         length: 0x00000000
```

Section 6.2 in DWARF v4 contains the full spec.

**Comment by trevorwhitaker** [comment]
As it turns out my issue was that dir_index was 0 so I had to then get the `DW_AT_comp_dir` from the CU top die. I overlooked the part in the DWARF docs that mentioned a dir_index of 0 means current dir which is why I was getting the incorrect path from the include_directories. Relevant doc snippet for posterity. 

```
The directory index represents an entry in the include_directories section. The index is
LEB128(0) if the file was found in the current directory of the compilation, LEB128(1) if it
was found in the first directory in the include_directories section, and so on. The
directory index is ignored for file names that represent full path names.
```

I will close this issue now. Thanks!-
