### ISSUE TITLE
Fixed some gaps, but the test files are not for publishing

### ISSUE THREAD

**Issue by sevaa** [eliben/pyelftools#261]
I've been using elftools to parse DWARF information in a certain Android codebase. Found some gaps in functionality (unsupported expression opcodes), fixed them in my fork. I wanted to submit a pull request for the fixes. There is a unit test for the fixes, but the SO files it works against are not to be published on Github. Advice?

**Comment by eliben** [comment]
Everything has to be public. The best way forward would be to synthesize some public reproducer binary that shows the tested characteristics.

**Comment by sevaa** [comment]
Understood. I'll try, but getting the toolchain to emit what you want is not an exact science. It's all implementation details, after all.
