### ISSUE TITLE
Change relocate_dwarf_sections default value

### ISSUE THREAD

**Issue by mephi42** [eliben/pyelftools#270]
My linux kernel debug info (Fedora 31, 5.4.13-201.fc31.x86_64) must not
be relocated, since its `e_type` is `ET_EXEC`, not `ET_REL`. Despite
that and for whatever reason, the relocation section for `.debug_info`
is present and contains completely bogus information.

Because of that, when using `get_dwarf_info()` I get e.g. incorrect
symbol names. As a workaround I now use
`get_dwarf_info(relocate_dwarf_sections=False)`, but it would be great
if default functioned correctly.

So I propose to change the default `relocate_dwarf_sections` value from
`True` to `None`, where `None` would mean "autodetect based on `e_type`
value".

Does that make sense?

**Comment by eliben** [comment]
I'm not sure about this. It seems like you're running into a rather rare case, and you have the option available to do what you want. Not sure the extra complexity is worth it for this case.
