### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by RamiRosenbaum** [eliben/pyelftools#278]
In construct_utils.py, missing import of **SizeofError**:
`from ..construct import (
    Subconstruct, ConstructError, ArrayError, Adapter, Field, RepeatUntil,
    Rename, SizeofError
    )
`

**Comment by eliben** [comment]
How does this manifest?

**Comment by rupran** [comment]
It definitely shows up as an error using pylint3:

```
E: 47,14: Undefined variable 'SizeofError' (undefined-variable)
```

as the type is used for throwing an error in RepeatUntilExcluding._sizeof():

https://github.com/eliben/pyelftools/blob/83ad8a220d0fd7a183bf249ad8bbb681227dc266/elftools/common/construct_utils.py#L46-L47
