### ISSUE TITLE
Proposal: An API for getting the filename of line-program entry members

### ISSUE THREAD

**Issue by woodruffw** [eliben/pyelftools#283]
Getting the filename associated with a line-program entry member is currently a little tedious:

1. Grab the file index (`lpe.state.file`)
2. Look up the file entry in the line program header
3. Look up the directory index in the file entry
4. Join the resolved directory to the basename in the file entry

This could be provided with relatively few changes on the `LineProgram` class, like so:

```python
lp = LineProgram(...)
lpe = lp.get_entries()[0]
filename = lp.entry_filename(lpe)
```

Thoughts? I'd be happy to contribute this feature.

**Comment by mdmillerii** [comment]
The API should look forward to how it will deal with DWARFv5 lie programs where the directory can be the result of a program.

**Comment by woodruffw** [comment]
> It may be useful to be able to retrieve the directory and filename independently (If someone wants to move their source tree from where it was compiled)

Yeah, the API could be broken into:

```python
lp.entry_directory(...)
lp.entry_basename(...)
lp.entry_filename(...)
```

Or some subset. I agree re: DWARFv5; will look into that.

**Comment by eliben** [comment]
I left a similar comment in another feature request recently. To repeat the salient point: in general I prefer to keep the APIs of pyelftools low level. There's a huge number of examples where getting some information from DWARF using pyelftools requires several steps & lookup, and all these examples could benefit from higher-level APIs. However, this is not what pyelftools was designed to do. It was designed to be low-level, on purpose, to keep the API surface as low as possible (of course it's big already!) and lower its maintenance burden.

Tasks such as these are better as examples in the `examples` directory, which even has its own tests to ensure it doesn't bit rot.

**Comment by eliben** [comment]
On a related note - there's been an unusual spike in activity on the issue tracker recently. I'm excited to see that folks work actively with pyelftools, but unfortunately my work schedule is very spiky so I apologize in advance for any delays. Working on pyelftools requires a significant context switch from my daily activities and I can only do it in bursts, once in a while. Don't expect quick turnaround from me on these issus/PRs, but I will get to them *eventually*.

Naturally, any help from folks familiar with the code will be much appreciated - in reviewing PRs, answering issues, etc.

**Comment by woodruffw** [comment]
Thanks for the response! Keeping pyelftools low level is an understandable goal -- I'm going to rescind this proposal in light of it. For others' reference, here's a quick (non-instance-method) version of the operation I describe above:

```python
# Invariant: file_index > 0
def lpe_filename(file_index, lp_header):
    file_entries = lp_header["file_entry"]
    if file_index - 1 > len(file_entries):
        return None

    # File and directory indices are 1-indexed.
    file_entry = file_entries[file_index - 1]
    directory = lp_header["include_directory"][file_entry["dir_index"] - 1]

    return os.path.join(directory, file_entry.name).decode()
```

Thanks for all the work you've done on pyelftools! It's been truly invaluable 😄

**Comment by eliben** [comment]
Thanks for the understanding. I'll be happy to accept something like that as a new example in `examples`. This is a good resource for folks who ask "how do I accomplish X with pyelftools", and such questions are frequent.

**Comment by woodruffw** [comment]
> Thanks for the understanding. I'll be happy to accept something like that as a new example in `examples`. This is a good resource for folks who ask "how do I accomplish X with pyelftools", and such questions are frequent.

Will do!
