### ISSUE TITLE
aarch64 and ppc64 support?

### ISSUE THREAD

**Issue by nickdesaulniers** [eliben/pyelftools#317]
Hi @eliben !
I wrote [a utility to help debug](https://github.com/ClangBuiltLinux/frame-larger-than) `-Wframe-larger-than=` warnings (which are pretty unhelpful in telling you what particular variables may be causing this, especially when many child calls have been inlined.  Apparently all of that info about local variables in captured in the debug info).

We used it for debugging a warning for a ppc64 Linux kernel build, but it seemed the object file failed to parse.  We [observed](https://groups.google.com/g/clang-built-linux/c/GjVJqQMvjvg/m/45gaOrW0AAAJ) the thrown ElfError: `Unsupported relocation type: 1`.

I haven't dug into reproducing yet, but I wanted to check first if pyelftools supports ppc64? I'm not sure if ppc64 uses a different target triple for endianess or not.  I also haven't dumped the relocation kinds, which may be helpful for this report.

**Comment by nickdesaulniers** [comment]
Looks like ppc is not supported: https://github.com/eliben/pyelftools/blob/430e3a550f9c7b64b4b3630d319442aa79e3db19/elftools/elf/relocation.py#L155-L178

**Comment by eliben** [comment]
Yep, no one added arm64 and ppc support yet. Should be fairly straightforward. Patches welcome!

**Comment by trevorwhitaker** [comment]
Hey @nickdesaulniers , I'm getting the same(ish) error on ppc.

Does the PR address `elftools.common.exceptions.ELFRelocationError: Unsupported relocation type: 38`?

If not, how would I go about patching in support for this?

Thanks!

**Comment by nickdesaulniers** [comment]
@trevorwhitaker sorry, no, I've only had time to implement some aarch64 support.  I haven't done a ton of testing, so I'll bet there's more relocations or endianness issues.  Take a look at #318; though it was helpful IIRC that many relocations were already implemented (there generally are a lot of relocation types for a given ISA target).

**Comment by trevorwhitaker** [comment]
Ok, thanks! I'll take a crack at ppc though I am quite new to this. Could you expand on your last point a bit, I'm not quite sure I understand?

"though it was helpful IIRC that many relocations were already implemented (there generally are a lot of relocation types for a given ISA target)."

**Comment by nickdesaulniers** [comment]
Yeah! Relocations are references to variables whose locations won't be known at a certain time.  For example, the compiler may not know the address of some variable at compile time, but the assembler, the linker, or the loader may be able to patch in the correct address.  If you disassemble any binary via `llvm-objdump -d`, make sure to always use `-r` as well to view the relocations.  Each relocation has a "type" which is an agreement between producer/consumer how to encode/decode the relocations.  This library needs the list of relocations for a given ISA that might be observed in a binary, and how to decode them.

@eliben probably has a blog post further on the subject.  See also https://nickdesaulniers.github.io/blog/2015/05/25/interpreter-compiler-jit/ where I had to manually resolve relocations for a basic JIT compiler.

**Comment by trevorwhitaker** [comment]
Hi @nickdesaulniers, I found some ppc docs that I think have everything I need (https://refspecs.linuxfoundation.org/ELF/ppc64/PPC-elf64abi.html#RELOC-TYPE). I have a couple of questions though if you don't mind answering.

1) Why did you only include the general registers and SP? (I am not sure if I should include the floating point registers)
2) For the relocation type, do I need to implement all in Figure 4-1 of the above link. Or are there only a certain number of useful ones? ie my failure was relocation type 38 so do I just need R_PPC64_ADDR64?

Thanks again

**Comment by trevorwhitaker** [comment]
Sorry, I didn't see your latest post until after I posted my most recent. Thanks for the explanation, makes a lot more sense now as to why this is needed! And that mostly answers my number 2 question I think. I really appreciate the help :)

**Comment by nickdesaulniers** [comment]
Good questions.  For 1, it's because there are now many many registers for aarch64; particularly all the SIMD registers.  In that sense, my patch is incomplete!  If you use those registers, then run pyelftools on that binary, it will fail with an error that the registers are unrecognized.  It's not too bad to add them to the list.

For a more precise reason why; my use case for this library is decoding DWARF debug information from Linux kernels.  The Linux kernel generally avoids the use of floating point and SIMD, though it is possible (see fun bugs like https://github.com/ClangBuiltLinux/linux/issues/735).  The reason for that is that you need to preserve register state on context switch, and the kernel can preempt itself (so even on single core machines you can have synchronization bugs), so the less work you have to do on context switch, the better.  When it comes to floating point registers, many ISAs' initial hardware floating point support was implemented via off-die coprocessors whose use was not as performant as the general purpose registers, so saving/restoring them was much more expensive.  I think that's less so the case today; now SIMD registers are so wide that they take a long time to save/restore and require a lot of memory per "task" (the Linux kernel's term for a thread of execution, not necessarily corresponding to a userspace process).  If you avoid their use in the kernel, the kernel can do less work when preempting itself (IIRC, it has tricks for doing this optimization for userspace, too).

> I am not sure if I should include the floating point registers

Depends on your use case.  For a minimum viable product, some PPC support is better than no PPC support, so in that spirit feel free to leave them off.  Though depending on your use case, which differs from mine, maybe you'll soon find you need FP support.

> Or are there only a certain number of useful ones?

Probably only certain ones you actually observe in a binary; the ones left for either the linker or loader. Depending on your use case, if you're trying to use `pyelftools` on object files (`.o`), then you may need to support relocations that the linker would have resolved when linking an executable.  Otherwise if you're running `pyelftools` against an executable files, then you'll just need to support the fewer relocations that the loader is expected to resolve.

ARM is bi-endian, and I didn't test support for that.  Are there relocation types that are specific to big endian (the default target is little endian)? Dunno, but wouldn't be surprised.  PPC is bi-endian, too, with the default target being big endian IIRC.

> ie my failure was relocation type 38 so do I just need R_PPC64_ADDR64?

Yep (though I didn't verify that 38 == R_PPC64_ADDR64).

**Comment by trevorwhitaker** [comment]
Awesome. Thank you so much for the info! Hopefully I can get this to work on my ppcle libraries 😄

**Comment by trevorwhitaker** [comment]
@eliben @nickdesaulniers I've tried to add support for PPC and in some of my shared libraries (little endian ppc) that I am testing on I am hitting an exception that I'm not sure how to go about debugging. Obviously the parsing is failing but I'm not really sure how I figure out why we are not reading the 8 bytes. Would you be able to point me in the right direction? My branch is at https://github.com/trevorwhitaker/pyelftools/commit/7b9dc631fd799f4b8c00af0c907b7fcda141b564 and the exception is

```
Traceback (most recent call last):
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/site-packages/pyelftools-0.26-py3.6.egg/elftools/construct/core.py", line 351, in _parse
    return self.packer.unpack(_read_stream(stream, self.length))[0]
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/site-packages/pyelftools-0.26-py3.6.egg/elftools/construct/core.py", line 293, in _read_stream
    raise FieldError("expected %d, found %d" % (length, len(data)))
elftools.construct.core.FieldError: expected 8, found 0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/site-packages/pyelftools-0.26-py3.6.egg/elftools/common/utils.py", line 40, in struct_parse
    return struct.parse_stream(stream)
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/site-packages/pyelftools-0.26-py3.6.egg/elftools/construct/core.py", line 190, in parse_stream
    return self._parse(stream, Container())
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/site-packages/pyelftools-0.26-py3.6.egg/elftools/construct/core.py", line 353, in _parse
    raise FieldError(ex)
elftools.construct.core.FieldError: expected 8, found 0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "nessie.py", line 917, in _createLineNumbersDbWorker
    dwarfinfo = self.getDwarfInfo(elffile)
  File "nessie.py", line 757, in getDwarfInfo
    dwarfinfo = elffile.get_dwarf_info()
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/site-packages/pyelftools-0.26-py3.6.egg/elftools/elf/elffile.py", line 207, in get_dwarf_info
    relocate_dwarf_sections)
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/site-packages/pyelftools-0.26-py3.6.egg/elftools/elf/elffile.py", line 628, in _read_dwarf_section
    section_stream, reloc_section)
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/site-packages/pyelftools-0.26-py3.6.egg/elftools/elf/relocation.py", line 141, in apply_section_relocations
    self._do_apply_relocation(stream, reloc, symtab)
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/site-packages/pyelftools-0.26-py3.6.egg/elftools/elf/relocation.py", line 203, in _do_apply_relocation
    stream_pos=reloc['r_offset'])
  File "/home/hotelppcle03/twhitake/python/pytest/lib/python3.6/site-packages/pyelftools-0.26-py3.6.egg/elftools/common/utils.py", line 42, in struct_parse
    raise ELFParseError(str(e))
elftools.common.exceptions.ELFParseError: expected 8, found 0
```

I only run in to this exception in certain libraries, I'm trying to reproduce in a standalone program but haven't been able to so far. I'm going to run llvm-dwarfdump on the libraries that fail and see if it can be parsed.

I can create a new issue for this if needed but since the PR I'm trying to create is related to this I figured I should post here.

Thanks!

**Comment by trevorwhitaker** [comment]
Interestingly the reloc offset trying to be parsed doesn't exist in the reloc table according to `objdump -r`. The value pyelftools is looking for is inside `eh_frame` and when I compare this against the objdump output, the offset pyelftools is looking for is much much larger than the largest offset in `eh_frame`. So my thinking currently is that pyelftools is reading the sections incorrectly. Still looking in to this but will take some time as I'm learning as I go

**Comment by trevorwhitaker** [comment]
Nevermind, I see that the offset pyelftools is looking for is the offset of the reloc + offset of eh_frames.

```
[16] .eh_frame         PROGBITS         000000000224c798  0223c798
       000000000015348c  0000000000000000  WA       0     0     8
```

```
OFFSET           TYPE              VALUE
0000000000000078 R_PPC64_REL64     .text+0x0000000000003f30
```
And 224c798 + 78 is what pyelftools wanted. So looks like I'm back to figuring out why this offset is invalid

**Comment by trevorwhitaker** [comment]
So I figured out the issue. pyelftools `r_offset` seems to be an absolute offset, but the section stream starts at the start of the section. So what we actually want is the relative offset. I'm not sure where/how we actually get r_offset value. I assume it is in `structs.py:_create_rel` but can't really figure out what is going on. @eliben or other pyelftools experts, I would appreciate some input here if you have some time to take a look. Thanks!

I'm also not sure if this issue exists on other platforms (I would assume so but never ran into it myself but there are tests so I don't know) or just a PPC specific problem.
