### ISSUE TITLE
Add support for DWARF version 5

### ISSUE THREAD

**Issue by gpollo** [eliben/pyelftools#325]
pyelftools still doesn't support DWARF version 5 as seen [here](https://github.com/eliben/pyelftools/blob/master/elftools/dwarf/dwarfinfo.py#L434). Is there anything considerable to be done except changing those lines and adding the new `DW_TAG` and `DW_AT`? If no work as been done, I might give it a try as I need some DWARF version 5 information.

**Comment by sevaa** [comment]
Locations section parsing need to be rewritten.

**Comment by pogo59** [comment]
There's actually a significant amount of change in DWARF v5.
New line table header format, which can move pathnames to a new section.
Location lists and range lists have a radically different encoding and use new section names.
References to .debug_str from .debug_info can be indirect through a .debug_str_offsets section.
Addresses can be in a separate .debug_addr section and referenced by index.
If you want to get super fancy there are several new unit types which can refer to debug info in a separate ".dwo" (dwarf object) file.

Those are the big items, off the top of my head.  There's a bunch of new FORMs to support the indirect references, and of course new DW_TAG and DW_AT items.

I know the DWARF side of things pretty well but I'm not such a great Python coder, and it's not clear my employer would give me time to work on this.  But I thought it was worth spelling out the scope a little more fully.

**Comment by woodruffw** [comment]
I'm taking an initial stab at this, starting with the changes to CU headers.

**Comment by pombredanne** [comment]
Since this has been merged, a new release would be awesome!

**Comment by woodruffw** [comment]
One thing to keep in mind: the support I added is *very* preliminary. I’m positive additional work will be needed to fully support DWARF5!

**Comment by pombredanne** [comment]
> One thing to keep in mind: the support I added is *very* preliminary. I’m positive additional work will be needed to fully support DWARF5! 

That's OK IMHO... at least we can start playing with these.

**Comment by sevaa** [comment]
For the paranoid among us, one could make DWARF 5 support explicitly opt-in. Like, a flag that is False by default.

That said, I, as a consumer of pyelftools, would rather take my chances with the experimental code as it is.

**Comment by noppej** [comment]
Hi, I would like to support @sevaa 's request for a release with experimental code. As a user of this, it is better to have a solution that **sometimes** works (experimental DWARF 5 support), than one that **never** works (no DWARF 5 support)

**Comment by eliben** [comment]
Version 0.28 was released with all the latest stuff inside

**Comment by sevaa** [comment]
How come this is still open? :)
