### ISSUE TITLE
Offset issue parsing child by iter_DIE_children

### ISSUE THREAD

**Issue by Merzhin79** [eliben/pyelftools#329]
I got an error in "iter_DIE_children" in one of my ELF when parsing a compilation UNIT. The error is on the offset of DW_AT_sibling of one of the child (DW_TAG_lexical_block in the example but can be other DIE type but not all DIE).

I got this when cur_offset is computed in "iter_DIE_children" as "DW_AT_sibling" exist (cur_offset = sibling.value + self.cu_offset):

DIE DW_TAG_lexical_block, size=13, has_children=True
    |DW_AT_sibling     :  AttributeValue(name='DW_AT_sibling', form='DW_FORM_ref_addr', value=970, raw_value=970, offset=939)

==> In above exemple when we look at the sibling, we see: 
- value=970
- offset=939
And so cur_offset is computed to 970 + 939 but this is an error here as the offset of sibling is in fact 970 (no need to make the addition). But on other DIE the addition need to be done to retrieve the offset.

It seems that I got:
- some die where cur_offset shall be equal to sibling.value
- some other die where cur_offset shall be equal to sibling.value + self.cu_offset

Here I don't know if the issue is in the ELF or in pyelftools itself ? After for the ELF, I use a commercial compiler/linker so I think DWARF information should be correct.
I extract the DWARF by using objdump and on this DIE, the offset are correct.

**Comment by Merzhin79** [comment]
I find something. The sibling.form value take two value in my ELF: DW_FORM_ref_addr or DW_FORM_ref4:
- DW_FORM_ref4: cur_offset = sibling.value + self.cu_offset
- DW_FORM_ref_addr : cur_offset = sibling.value

I patch "iter_DIE_children" for my use but need to confuirm if it's an ELF DWARF info issue or pyelftools issue

**Comment by sevaa** [comment]
Looks like PR #268 . Merged into master but not released.

**Comment by Merzhin79** [comment]
Yes, you are right, then I close this one
