### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by rupran** [eliben/pyelftools#337]
Seeing that the last release was almost one year ago (https://pypi.org/project/pyelftools/#history) and using some of the features that were implemented over the last year in my own projects, I was wondering if you have any plans to do a new release anytime soon.

Thanks for your ongoing work on pyelftools!

**Comment by eliben** [comment]
I think we can do a release, no problem. Would you like to see anything else of the ongoing things go in before a release, or is cutting it at the current commit of the master branch ok?

**Comment by rupran** [comment]
We might want to take a look at #336 as there were some changes around DWARF since the last release. Other than that, I don't think there is too much going on regarding pull requests right now, so I would be happy with a release from the current master (modulo a fix for #336).

**Comment by eliben** [comment]
Version 0.27 released

Please test and LMK if you see any issues. If it all looks OK, please close the issue

**Comment by rupran** [comment]
Looks good to me, I'll close this for now and reopen if anything comes up (which I don't think will happen).

Thanks!
