### ISSUE TITLE
Introduce sections.iter_sections(self, type=None) method

### ISSUE THREAD

**Issue by evelikov** [eliben/pyelftools#344]
Please consider add an optimised menthod iter_sections() which optionally takes the section type, similar to the existing iter_tags().

I have noticed that, when working with raw archives the overhead or looping over the elf header becomes quite obvious. In one particular [use-case](https://lists.archlinux.org/pipermail/arch-projects/2021-January/005411.html) switching from iter_tags() to iter_tags(type) has resulted in massive speed increase.

While I don't expect the results to be quite as significant, the consistent API in itself is worth it.

Thanks in advance

**Comment by eliben** [comment]
While I haven't looked at the use-case and existing API in detail, feel free to send a PR. I'll review it in detail then

**Comment by evelikov** [comment]
Thanks for the prompt reply eliben. I've already had a look through the code-base and it's a little over my python skills at the moment. So in the short-term it's unlikely that I'll submit PR - more than happy to test though :grinning:

**Comment by evelikov** [comment]
@rupran you're a star - patch works just fine.

As anticipated there is no performance boost, even with the pathological example - but the shorter code is a win in itself.

**Comment by rupran** [comment]
No worries, always happy to help!
