### ISSUE TITLE
Missing sources for examples/sample_exe64.elf

### ISSUE THREAD

**Issue by zyga** [eliben/pyelftools#350]
I'm building a Debian package and to satisfy packaging requirements, I'd like to know the sources for `examples/sample_exe64.elf`.

**Comment by eliben** [comment]
I'm not sure I could find it now, sorry.

**Comment by zyga** [comment]
Could that binary be replaced with a trivial binary with new sources? Does it have some specific property that needs to be replicated? I can contribute this change if you would be willing to take it.

**Comment by eliben** [comment]
Yes, it can be replaced. The only real property is that it's a suitable binary for all the examples to show something.

If you submit a different binary and adjust all the example tests to pass, I'll gladly review the PR. No objections

**Comment by eliben** [comment]
I will say, though, that it's not entirely clear to me why you need this example file in your package. For folks who want to use `pyelftools` the example is certainly unnecessary, and if people really need it, it's just a `curl` away from GitHub

**Comment by zyga** [comment]
@eliben I was going to make a Debian package and since the binary has no corresponding source I have two options:

1) create a dfsg derivative tarball which essentially re-packages the upstream tarball without problematic parts
2) provide the original source for the binary (a bit exceptional but fine)

Debian puts a lot of effort on copyright and licenses, so while your typical users may not care much, this is very important for me.
