### ISSUE TITLE
Is it possible to Modify Dwarf sections?

### ISSUE THREAD

**Issue by victorChB** [eliben/pyelftools#355]
So far I have been using the library to parse DWARF information. But I would like to know if its possible to modify specific attributes of the DWARF file and generate a new DWARF file?

 For example the  DW_AT_LOW_PC attribute of a specific function. I'm looking for a way to implement this as I am compiling Position independent code (PIC) and would like to rebase the address of the functions so I can tell GDB where to locate them at runtime.

**Comment by eliben** [comment]
pyelftools doesn't generally support editing ELF and DWARF.
