### ISSUE TITLE
DW_TAG_Variable has wrong specification

### ISSUE THREAD

**Issue by pylessard** [eliben/pyelftools#358]
I've loaded the dwarf info from the attached file. 
We can see this in dwarf : 

    <1><c4>: Abbrev Number: 9 (DW_TAG_variable)
    <c5>   DW_AT_specification: <0xac>
    <c9>   DW_AT_location    : 9 byte block: 3 30 40 40 0 0 0 0 0 	(DW_OP_addr: 404030)

But when parsing with elftool. I find that die at C4 has a specification value of 0x71 instead of 0xac

    DIE DW_TAG_variable, size=15, has_children=False
        |DW_AT_specification:  AttributeValue(name='DW_AT_specification', form='DW_FORM_ref4', value=113, raw_value=113, offset=197)
        |DW_AT_location    :  AttributeValue(name='DW_AT_location', form='DW_FORM_exprloc', value=[3, 48, 64, 64, 0, 0, 0, 0, 0], raw_value=[3, 48, 64, 64, 0, 0, 0, 0, 0], offset=201)

This  seems like a bug to me.

Regards

DWARF : [dwarf.txt](https://github.com/eliben/pyelftools/files/6395915/dwarf.txt)
.elf : [testapp.zip](https://github.com/eliben/pyelftools/files/6399931/testapp.zip)

**Comment by rupran** [comment]
I think this is the same "issue" as described here: https://github.com/eliben/pyelftools/issues/241#issuecomment-565637775

Quote:
> A `DW_AT_specification` attribute is of class `reference`, and a `reference` is relative to the first byte of the cu header unless its of form `DW_AT_refaddr`, where its relative to the `.debug_info` section.

And indeed, by adding the offset of the surrounding compile unit you also get the value `0xac` (`0x3b` + `0x71`):
```
  Compilation Unit @ offset 0x3b:
   Length:        0x95 (32-bit)
   Version:       4
   Abbrev Offset: 0x2c
   Pointer Size:  8 
```

**Comment by pylessard** [comment]
Ah!
I did not understand this. Thank you for the reply.
Regards
