### ISSUE TITLE
Add DW_AT_virtual (0x30) to the ENUM_DW_AT

### ISSUE THREAD

**Issue by sevaa** [eliben/pyelftools#379]
As far as I can tell, the DIE attribute DW_AT_virtual was deprecated, but I've seen it in the wild.

**Comment by eliben** [comment]
Any reference information about it anywhere? A google search comes up impressively empty

**Comment by sevaa** [comment]
https://dwarfstd.org/doc/dwarf_1_1_0.pdf

See page 31.

The reason searches come up empty, in DWARFv1 attribute names were prefixed with AT_, not with DW_AT_. :) So `DW_AT_virtual` was never a findable keyword, `AT_virtual` was. The left shift by 4 for the value was yet another DWARFv1 thing that went away; note the values on other attributes compared to what we have since DWARFv2.

**Comment by eliben** [comment]
Ah, got it. Thanks.
