### ISSUE TITLE
Accessing DWARF information in non-ELF file

### ISSUE THREAD

**Issue by BasyaP** [eliben/pyelftools#383]
Is it possible to use this library to parse and access the DWARF debugging information in a file in a different format than ELF?  For example, DWARF debugging sections in a COFF executable?  Supposing I have code to parse the COFF file and find the DWARF sections in the code, is there some way to pass this to the DWARF handling code in your library?

The User Guide says, "Care was taken to make DWARFInfo independent of ELFFile, to allow its usage independently of any specific container (for example, to parse DWARF data directly emitted into memory or dumped to a file)."  However, it is not clear from the documentation how to use DWARFInfo without ELFFile, nor do I see an example demonstrating this.  Unless I have missed something?

**Comment by sevaa** [comment]
Entirely possible. See the example at https://github.com/sevaa/dwex/blob/master/dwex/formats.py . It parses DWARF out of Mach-O and PE (COFF). Tested on real life executables.

**Comment by BasyaP** [comment]
Thank you.  I will look at your example and see if I can do something similar.

**Comment by BasyaP** [comment]
Hello.  I don't know if it is possible to reopen this or just ask for more help even if it is closed.  The COFF files I am working with are not PE files, so the filebytes library did not parse them.  I tried two directions to make this work.  First I parsed the files with a different library for parsing COFFs, and tried to pass the correct parameters to the dwarf info class.  I had difficulty getting this working so I tried a different direction (thinking it would be smoother :-) ).  I made a variation of the PE code from filebytes, modifying it to parse a non-PE COFF file.  I _think_ this is working, but I am still not able to roll out my symbols as expected, from the dwarf info object.

Since you gave me a working example with a PE file, I thought I could run that on a PE file with DWARF debugging information and trace it through in the debugger, but I have not yet found an environment where I can build such a file.  Can you direct me to one (or to somewhere I can get an example PE file with DWARF debugging info?

Thank you.

**Comment by sevaa** [comment]
What platform do those files come from in the first place? Usually, when you have a compiler that emits a certain format, there is a debugger alongside.

I know of two platforms that use the combination of PE and DWARF (both on Windows): 
 - Free Pascal, which comes with its own linker and its own gdb-based debugger
 - GCC on Cygwin, gdb as the debugger, but I would use a shell on top of gdb, notably ddd

The transition from COFF to PE is not automatic (it's, well, linking). Chances are, whatever linker you are using doesn't respect the conventions of the compiler. Specifically, the regular Microsoft linker (the most popular PE generation utility out there, I'd surmise) would almost certainly bungle DWARF information, as it was never meant to handle it. You might have better luck with whatever linker comes with Cygwin.

That said, I think using a COFF parser and preparing a DWARFData by hand (your first approach) is a better avenue. Now, I recall there are many flavors of COFF out there, with different vendor extensions. Are you sure your COFF parser can handle whatever those particular COFFs have?

Consider debugging your COFF parsing logic. Maybe the COFF parsing itself needs some tweaking.

**Comment by BasyaP** [comment]
Thank you.

In answer to your first question, we are not actually writing a debugger; we are writing a tool to provide information about the program to an in-house tool which we have, to be used for testing/debugging purposes when we are not connected with a JTAG and a debugger.  We need some of the same information a debugger would use.  This is firmware, which is why we have a COFF file and not PE.  It doesn't run under Windows.

Thank you for the information on gcc and Free Pascal; I will have to look at them.

I have two options now for parsing the COFF file.  I _think_ both are working properly; either I am missing something there or I am not passing the information correctly to the DwarfInfo class. (As I mentioned previously, one of the options for parsing the COFF file is a modification of the PE parser from the filebytes library, and the other is someone else's library).

Is there somewhere I can get a better understanding of what I should be passing to the DWARFInfo class?  What is the stream?  Is it the same for all the different sections passed, and the offset is the offset into the stream, or is the stream set up starting from the correct offset in the file (I don't know whether that is even possible)?

**Comment by sevaa** [comment]
The first argument of Dwarfinfo is the configuration object (`DwarfConfig`); the rest are DWARF relevant sections. It goes:
```
class DWARFInfo(object):
    """ Acts also as a "context" to other major objects, bridging between
        various parts of the debug infromation.
    """
    def __init__(self,
            config,
            debug_info_sec,
            debug_aranges_sec,
            debug_abbrev_sec,
            debug_frame_sec,
            eh_frame_sec,
            debug_str_sec,
            debug_loc_sec,
            debug_ranges_sec,
            debug_line_sec,
            debug_pubtypes_sec,
            debug_pubnames_sec):
```
The config is an instance of `DwarfConfig`, the sections are passed as `DebugSectionDescriptor` objects. `io.BytesIO` is a built in class in Python that provides a stream on top of a memory buffer (a `bytes`/`bytearray` object). Since parsing involves a lot of random access, you'd be better off keeping the sections in the memory anyway.

The only sections that are strictly necessary (as of DWARFv2) are info and abbrev. Str is pretty much necessary for a realistic program.

Are your COFF files built executables? I've never tried parsing one; does it have the notion of sections? Do sections have names? Can you read them into memory blocks? Try matching section names against what the DWARF sections are. If there is only one, chances are it's DWARFv1 (V2, like I said, can never work with just one section) and pyelftools would be of little help.

I do have a DWARFv1 parser that tries to mimic pyelftools at https://github.com/sevaa/dwex/blob/master/dwex/dwarfone.py

In my experience with parsing DWARF from various executable formats, I've seem DWARF sections called similar but slightly different names in various implementations. So check section names in your files and see where it takes you.
