### ISSUE TITLE
Link to DWARF standard on wiki?

### ISSUE THREAD

**Issue by kimballa** [eliben/pyelftools#394]
The [user guide](https://github.com/eliben/pyelftools/wiki/User's-guide) says "There's no way around it - to even understand the API one must have some grasp of the DWARF standard." 

It might be helpful to add a link there directly to the DWARF standard docs: https://dwarfstd.org/Download.php

(Unfortunately, I don't know how to send a pull request for wiki modifications since the wiki doesn't come along with a repo fork -- otherwise I'd add it myself.)

This library -- especially the DWARF decoding -- has been super helpful to me. Thanks for making it!

Thanks
\- Aaron

**Comment by eliben** [comment]
I'm pretty sure you should be able to edit the Wiki through the GitHub interface; I know that others have edited in the past. Can you try?

**Comment by kimballa** [comment]
I think you may have permissions set up so that only collaborators can edit the wiki.

For example, on a wiki for one of my own repositories, I see these buttons:
![image](https://user-images.githubusercontent.com/87376/151853329-4c43f710-8f79-4512-9864-acdc103778ce.png)

... but no such buttons show up for me in the upper-right corner of the page for your wiki pages (and I double-checked that I'm logged into github so it's not about anonymous access.)
