### ISSUE TITLE
FieldError: expected 4, found 0

### ISSUE THREAD

**Issue by Aida-yy** [eliben/pyelftools#396]
---------------------------------------------------------------------------
FieldError                                Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/elftools/construct/core.py in _parse(self, stream, context)
    350         try:
--> 351             return self.packer.unpack(_read_stream(stream, self.length))[0]
    352         except Exception as ex:

~/anaconda3/lib/python3.7/site-packages/elftools/construct/core.py in _read_stream(stream, length)
    292     if len(data) != length:
--> 293         raise FieldError("expected %d, found %d" % (length, len(data)))
    294     return data

FieldError: expected 4, found 0

During handling of the above exception, another exception occurred:

FieldError                                Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/elftools/common/utils.py in struct_parse(struct, stream, stream_pos)
     39             stream.seek(stream_pos)
---> 40         return struct.parse_stream(stream)
     41     except ConstructError as e:

~/anaconda3/lib/python3.7/site-packages/elftools/construct/core.py in parse_stream(self, stream)
    189 
--> 190         return self._parse(stream, Container())
    191 

~/anaconda3/lib/python3.7/site-packages/elftools/construct/core.py in _parse(self, stream, context)
    646             else:
--> 647                 subobj = sc._parse(stream, context)
    648                 if sc.name is not None:

~/anaconda3/lib/python3.7/site-packages/elftools/construct/core.py in _parse(self, stream, context)
    352         except Exception as ex:
--> 353             raise FieldError(ex)
    354     def _build(self, obj, stream, context):

FieldError: expected 4, found 0

During handling of the above exception, another exception occurred:

ELFParseError                             Traceback (most recent call last)
<ipython-input-8-1b1c9231a6d0> in <module>
      4 #     process(f)
      5 #     readelf = ReadElf(file, stream or sys.stdout)
----> 6     elffile = ELFFile(open(f, 'rb'))

~/anaconda3/lib/python3.7/site-packages/elftools/elf/elffile.py in __init__(self, stream)
     86 
     87         self._section_header_stringtable = \
---> 88             self._get_section_header_stringtable()
     89         self._section_name_map = None
     90 

~/anaconda3/lib/python3.7/site-packages/elftools/elf/elffile.py in _get_section_header_stringtable(self)
    690         stringtable_section_num = self.get_shstrndx()
    691         return StringTableSection(
--> 692                 header=self._get_section_header(stringtable_section_num),
    693                 name='',
    694                 elffile=self)

~/anaconda3/lib/python3.7/site-packages/elftools/elf/elffile.py in _get_section_header(self, n)
    551             self.structs.Elf_Shdr,
    552             self.stream,
--> 553             stream_pos=self._section_offset(n))
    554 
    555     def _get_section_name(self, section_header):

~/anaconda3/lib/python3.7/site-packages/elftools/common/utils.py in struct_parse(struct, stream, stream_pos)
     40         return struct.parse_stream(stream)
     41     except ConstructError as e:
---> 42         raise ELFParseError(str(e))
     43 
     44 

ELFParseError: expected 4, found 0

**Comment by Aida-yy** [comment]
Sure, This file will trigger error. 
[sample.zip](https://github.com/eliben/pyelftools/files/8058349/sample.zip)

**Comment by rupran** [comment]
Thank you for providing the file!

So from looking at it, I think it's simply an incomplete ELF file. `readelf -W -a` on the unpacked file shows (among other things) the following:

```
<...>
  Start of section headers:          4096504 (bytes into file)
<...>
Program Headers:
<...>
  LOAD           0x000000 0x0000000000400000 0x0000000000400000 0x3e0f7c 0x3e0f7c R E 0x200000
  LOAD           0x3e1000 0x00000000009e1000 0x00000000009e1000 0x007078 0x01bef0 RW  0x200000
```

pyelftools will try to read the section header table from the provided offset inside the file, the whole ELF file, however, is only `1296126` bytes large so the offset for the section header table points way beyond the end of the file. Additionally, the first LOAD segment tries to map `0x3e0f7c` == `4067196` bytes into memory which is again way more than there are bytes in the file. Was this file downloaded from somewhere but the download didn't fully complete?

**Comment by Aida-yy** [comment]
Thank you !

You're right. This file is downloaded from cloud server, it's corrupted. Linux readelf also can't parse it correctly.
![image](https://user-images.githubusercontent.com/55907868/153853274-d2940fd3-3b20-4ce2-a708-ba3ad65f3978.png)

**Comment by Aida-yy** [comment]
There are many file trigger this error, I will check them.

Do you have any document about how pyelftools works, I want to learn it. Thank you!

**Comment by eliben** [comment]
> There are many file trigger this error, I will check them.
> 
> Do you have any document about how pyelftools works, I want to learn it. Thank you!

There's some documentation on the Wiki: https://github.com/eliben/pyelftools/wiki

Other than that, I recommend getting closely acquainted with the ELF standard - pyelftools is just a fairly simple implementation thereof.

**Comment by Aida-yy** [comment]
> There's some documentation on the Wiki: https://github.com/eliben/pyelftools/wiki
> Other than that, I recommend getting closely acquainted with the ELF standard - pyelftools is just a fairly simple implementation thereof.

Thank you!
