### ISSUE TITLE
dwarf v5 missing code in abbreviations table

### ISSUE THREAD

**Issue by wideglide** [eliben/pyelftools#398]
I'm attempting to use pyelftools on a binary compiled with GCC 11 which uses dwarf version 5.  I get a key error in the abbreviation table lookup.  I'm not sure how to debug further.  It seems it is reading the abbrev stream just fine?  I'm using v0.28.

Here's an interactive session:
```python
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from elftools.elf.elffile import ELFFile
>>> fp = open("busybox-1_21_stable_gcc-11.2.0_mips_64_O1_busybox_unstripped.elf", "rb")
>>> elffile = ELFFile(fp)
>>> dwarf = elffile.get_dwarf_info()
>>> from ipdb import launch_ipdb_on_exception
>>> with launch_ipdb_on_exception():
...   lines = [dwarf.line_program_for_CU(CU) for CU in dwarf.iter_CUs()]
...
KeyError(68)
> /data/venv/lib/python3.8/site-packages/elftools/dwarf/abbrevtable.py(36)get_abbrev()
     35         """
---> 36         return self._abbrev_map[code]
     37

ipdb> self._abbrev_map.keys()
dict_keys([1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 23, 24, 28, 31, 32, 33, 34, 35, 36, 38, 42, 43, 45, 46, 47, 49, 51, 53, 54, 56, 58, 59, 61, 62, 64, 67, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97])
ipdb>
```

**Comment by sevaa** [comment]
68 is 0x44 is `DW_AT_namelist_item`.

**Comment by sevaa** [comment]
Does `readelf` and/or `dwarfdump` have a problem with that file? Can you share the offending file?

**Comment by wideglide** [comment]
`readelf` version 2.34 and `llvm-dwarfdump-12` process the file fine.

`llvm-dwarfdump-9` has issues:

```
error: decoding address ranges: invalid range list offset 0x1c556
error: dumping support for LLE of kind 1 not implemented
```

[busybox-1_21_stable_gcc-11.2.0_x86_64_O3_busybox_unstripped.gz](https://github.com/eliben/pyelftools/files/8234207/busybox-1_21_stable_gcc-11.2.0_x86_64_O3_busybox_unstripped.gz)

**Comment by tomstorey** [comment]
Hi

I am also hitting this issue with 0.28, in my case the missing key is 4.

The binary is compiled for 68K if that matters? Output and binary are attached.

`readelf.py --debug-dump info` partly decodes, and then errors

`readelf.py --debug-dump decodedline` only prints a table header and then errors

`readelf.py --debug-dump frames` seems to decode fine without errors

`readelf.py --debug-dump frames-interp` also seems to decode without any errors

`readelf.py --debug-dump aranges` seems to decode without any errors

`pubtypes`, `pubnames` and `loc` produce no output

All other interactions seem fine.

Test code:

```
$ python3
Python 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from elftools.elf.elffile import ELFFile
>>> file = open("bmbinary", "r+b")
>>> elffile = ELFFile(file)
>>> dwarfinfo = elffile.get_dwarf_info()
>>> for cu in dwarfinfo.iter_CUs():
...   print(dwarfinfo.line_program_for_CU(cu))
... 
<elftools.dwarf.lineprogram.LineProgram object at 0x10984b160>
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/elftools/dwarf/dwarfinfo.py", line 241, in line_program_for_CU
    top_DIE = CU.get_top_DIE()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/elftools/dwarf/compileunit.py", line 92, in get_top_DIE
    top = DIE(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/elftools/dwarf/die.py", line 94, in __init__
    self._parse_DIE()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/elftools/dwarf/die.py", line 234, in _parse_DIE
    abbrev_decl = self.cu.get_abbrev_table().get_abbrev(self.abbrev_code)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/elftools/dwarf/abbrevtable.py", line 36, in get_abbrev
    return self._abbrev_map[code]
KeyError: 4
```

[bmbinary.zip](https://github.com/eliben/pyelftools/files/8402079/bmbinary.zip)
[readelf.txt](https://github.com/eliben/pyelftools/files/8402080/readelf.txt)

**Comment by sevaa** [comment]
PR #400 fixes this, I've retested both attached files with the latest master - they parse.

**Comment by eliben** [comment]
Thanks @sevaa -- I'll close this issue.

@wideglide feel free to reopen if this is still a problem on the master branch
