### ISSUE TITLE
Deprecation of Python 2.7 and repository rewrite / refactor; also, why no docs?

### ISSUE THREAD

**Issue by M3TIOR** [eliben/pyelftools#399]
I was curious if this repository was at all considering removing the limitations imposed by keeping Python 2.7 backwards compatibility in place. It'd clean things up quite a bit. While potentially a hassle to implement, it could bring in more contributors. I think this project is really cool and a bit intimidating because of all the backwards compatibility requirements. Python 2.7 has been completely deprecated by the Python development team since January 1st, 2020. While this is a local python script, and not something that needs to worry about security all too much, it still should be noted that since the EoL is here, if there is a big vulnerability discovered within the python 2.7 interpreter, it'll be harder to maintain.

I just feel like there's no good reason to keep Python2.7 support alive unless it's for legacy systems; but for them, version management solves that problem. There's literally no reason to continue supporting it for a project like this. Python EoL has done passed the world by.

Admittedly I'm also a bit frustrated that such a good library doesn't have Doxygen / Sphinx style documentation. It's incredibly annoying to have to crawl the entire code-base while looking for a specific class or function. I don't use an IDE; maybe this could be better if I did, but I shouldn't have to require an IDE to navigate source code when the technology already exists to prevent it.

If there's only one true maintainer / this is a small project, I understand as I've started many. But this project has a lot more support and need than any of mine do and simply adding documentation into the standard contribution guidelines would fix this problem.

Sorry if this came off as condescending or mean. I'm just exhausted from working my whole day and grumpy. I appreciate that this repo exists in the public domain and (all?) you maintainers work so hard on it.

**Comment by eliben** [comment]
>

**Comment by eliben** [comment]
> I was curious if this repository was at all considering removing the limitations imposed by keeping Python 2.7 backwards compatibility in place. It'd clean things up quite a bit. While potentially a hassle to implement, it could bring in more contributors. I think this project is really cool and a bit intimidating because of all the backwards compatibility requirements. Python 2.7 has been completely deprecated by the Python development team since January 1st, 2020. While this is a local python script, and not something that needs to worry about security all too much, it still should be noted that since the EoL is here, if there is a big vulnerability discovered within the python 2.7 interpreter, it'll be harder to maintain.
> 
> I just feel like there's no good reason to keep Python2.7 support alive unless it's for legacy systems; but for them, version management solves that problem. There's literally no reason to continue supporting it for a project like this. Python EoL has done passed the world by.
> 

I'm thinking about this once in a while; so far there was never an issue with keeping 2.7 compatibility - in other words it has been rather uneventful. I don't ever recall a contributor saying that it was a problem for them. I'm OK with removing the compatibility if there's a good reason for it - for example, some new feature that needs to be implemented wherein the compatibility makes things harder.

> Admittedly I'm also a bit frustrated that such a good library doesn't have Doxygen / Sphinx style documentation. It's incredibly annoying to have to crawl the entire code-base while looking for a specific class or function. I don't use an IDE; maybe this could be better if I did, but I shouldn't have to require an IDE to navigate source code when the technology already exists to prevent it.
> 
> If there's only one true maintainer / this is a small project, I understand as I've started many. But this project has a lot more support and need than any of mine do and simply adding documentation into the standard contribution guidelines would fix this problem.
> 
> Sorry if this came off as condescending or mean. I'm just exhausted from working my whole day and grumpy. I appreciate that this repo exists in the public domain and (all?) you maintainers work so hard on it.

The code is reasonably well documented with docstrings (for classes and methods, etc.); if anyone wants to contribute a script that auto-generates documentation HTML from those, that's fine with me.

**Comment by sevaa** [comment]
The issue of Python 2 compatibility holding the library back came up in #286 and #279. Can't sensibly use the `bytes` datatype while compatibility with v2 has to be kept.

**Comment by eliben** [comment]
@sevaa these seem to mention potential changes to the pyelftools API, unless I'm mistaken. At this point in the life of this rather mature project I'd say that breaking compatibility is probably not the best idea anyway.

**Comment by M3TIOR** [comment]
I have to point out the latest version you've released is `0.28.0`. I don't think you're using [Semantic Versioning](https://semver.org), but most projects do and you really should be at least `1.0.0` if the existing API is here to stay. Prefacing a version with zero usually implies the project is in beta. **This project is mature and it's API should be stable.**  Though with that said, if I had the time I'd rewrite it from scratch to follow common conventions inherited from the Python standard library. The fact that `ELFFile` can only be instantiated using an existing stream and doesn't do dynamic file queries is a little absurd. Maybe that's a limitation of the ELF file architecture, but as currently presented the API doesn't meet my standards for `1.0.0` release. That's just me. That may seem a little condescending but I know @eliben you've put a lot of effort into this project I'm not saying it's been all for nothing or that the project sucks. I just think this codebase needs a little TLC and you're probably too wiped out from work to offer that. *Same for me until I get my tech support business off the ground.*

**Comment by sthagen** [comment]
> @sevaa these seem to mention potential changes to the pyelftools API, unless I'm mistaken. At this point in the life of this rather mature project I'd say that breaking compatibility is probably not the best idea anyway.

:+1: 

And, semantic versioning dances should not apply to "workhorses" like this project, which offers more porcelain than plumbing tools, right? 

If this would be a tool everyone and her dog would desperately use deep in their tools (instead of writing their own code), semantic versioning might be interesting. 

But, as long as it does not use [sentimental versioning](http://sentimentalversioning.org), I can hardly imagine any one complaining for real reasons. 

I would even be happy with hash versioning like e.g. BoringSSL does. 

I think this has always been a great resource, thanks for sharing to @eliben, it is in the public domain, and maybe we users might issue less "not complaining, but ..." type of feedback?
