### ISSUE TITLE
Error reading line programs from binary compiled with gcc 11.2

### ISSUE THREAD

**Issue by wheirman** [eliben/pyelftools#409]
I'm getting the following error when reading line programs (`readelf.py --debug-dump=decodedline`) from a binary compiled with gcc 11.2.0 on Ubuntu 22.04:

`ELF error: ('missing terminator', ArrayError('missing terminator', FieldError('expected 1, found 0',)))`

The binary is attached here: [fft.zip](https://github.com/eliben/pyelftools/files/8752301/fft.zip)

I tried the code from #408 as well but that didn't help. `readelf.py --debug-dump=info` works fine on the same binary.

**Comment by sevaa** [comment]
Confirmed, the issue exists, and it's unrelated to #408. The line program format has been revised in DWARF5, we knew this was coming, now might as well be the time.

**Comment by sevaa** [comment]
@wheirman: mind if I make a test case out of your binary?

**Comment by wim-heirman-at-intel** [comment]
I'm not sure what the licensing is on that fft example. But a simple hello world gives the same error, you can use this one:
[test-dwarf5-lineprogram.zip](https://github.com/eliben/pyelftools/files/8767982/test-dwarf5-lineprogram.zip)

This was compiled with just `-g` as an option.

```
$ gcc --version
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by eliben** [comment]
Can you please verify that #411 fixes it (it landed on the master branch)?

**Comment by Cirn09** [comment]
Work fine! 👍

**Comment by eliben** [comment]
Closing this for now. Please reopen if you see it still doesn't work on the main branch
