### ISSUE TITLE
Support DWARF5 standardization of GNU extension expression opcodes

### ISSUE THREAD

**Issue by rdunklau** [eliben/pyelftools#410]
In dwarfv5, a number of GNU extensions have been standardized.
I don't know how to test for them to be honest, but it would be nice to add synonyms to the GNU extension opcodes we already parse.

It seems to me that the following should be added:

DW_OP_GNU_entry_value => DW_OP_entry_value
DW_OP_GNU_const_type => DW_OP_const_type
DW_OP_GNU_regval_type => DW_OP_regval_type
DW_OP_GNU_deref_type => DW_OP_deref_type
DW_OP_GNU_implicit_pointer => DW_OP_implicit_pointer
DW_OP_GNU_convert => DW_OP_convert

**Comment by rdunklau** [comment]
Thanks ! I did not provide a PR since it's trivial to add, and the problem is actually having a test case for it as you noted. I guess worst case scenario would be to manually replace opcodes in the binary with the GNU_ versions and run through it ?

**Comment by sevaa** [comment]
EDIT: rebuilt the same code for Linux/x64 with DWARF5, got a test binary. At least 4 out of 6 opcodes are there. Stay tuned for a PR.

**Comment by sevaa** [comment]
I'd like to. Barring more surprises from GNU, this shouldn't take long.

**Comment by rdunklau** [comment]
I have a rudimentary implementation outside of pyelftools for this, let me make a proper patch for it.

**Comment by sevaa** [comment]
I'm already halfway :)

**Comment by rdunklau** [comment]
Great :-) Please ping me for the review if you want.

**Comment by vegard** [comment]
Hi, I ran into issues trying to use the `dwarf_lineprogram_filenames.py` example on files from these archives:
* http://ftp.de.debian.org/debian/pool/main/l/linux/linux-image-5.17.0-3-amd64-dbg_5.17.11-1_amd64.deb
* http://ddebs.ubuntu.com/pool/main/l/linux/linux-image-unsigned-5.15.0-37-generic-dbgsym_5.15.0-37.39_amd64.ddeb
I'm pretty sure the errors are related to DWARF5 as I'm getting various errors (including what looks like opcode-related ones):

On `/usr/lib/debug/lib/modules/5.17.0-3-amd64/kernel/drivers/edac/edac_mce_amd.ko` from the 5.17.11 deb above:
```
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elftools/dwarf/dwarfinfo.py", line 241, in line_program_for_CU
    top_DIE = CU.get_top_DIE()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elftools/dwarf/compileunit.py", line 92, in get_top_DIE
    top = DIE(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elftools/dwarf/die.py", line 94, in __init__
    self._parse_DIE()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elftools/dwarf/die.py", line 242, in _parse_DIE
    raw_value = struct_parse(structs.Dwarf_dw_form[form], self.stream)
KeyError: 'DW_FORM_line_strp'
```
and `/usr/lib/debug/lib/modules/5.17.0-3-amd64/kernel/net/atm/clip.ko`:
```
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elftools/dwarf/dwarfinfo.py", line 241, in line_program_for_CU
    top_DIE = CU.get_top_DIE()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elftools/dwarf/compileunit.py", line 92, in get_top_DIE
    top = DIE(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elftools/dwarf/die.py", line 94, in __init__
    self._parse_DIE()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elftools/dwarf/die.py", line 234, in _parse_DIE
    abbrev_decl = self.cu.get_abbrev_table().get_abbrev(self.abbrev_code)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elftools/dwarf/abbrevtable.py", line 36, in get_abbrev
    return self._abbrev_map[code]
KeyError: 172
```

You can use `dpkg-deb -x file.[d]deb /tmp/output-dir/` to extract the archives on a dpkg-based systems (Debian/Ubuntu).
Just wanted to add this as it might be a good test.

**Comment by sevaa** [comment]
@rdunklau: got any test binaries? Preferably one with the whole gamut of `DW_LLE_` entry types?

@vegard: we just had a PR with support for the V5 lineprogram logic, merged yesterday. Can you pull the latest master and test with that?

**Comment by rdunklau** [comment]
@sevaa no test binary unfortunately. I started implementing the basics because one of the binaries I'm working with had it (compiled with gcc 12.1).
Not sure what triggers it to generate a location list though...

**Comment by sevaa** [comment]
`.debug_loclists` works, but there is another section that was replaced in DWARF5: `.debug_rnglists`. Most disturbingly, the fact that it was ignored went undetected by the tests.

**Comment by eliben** [comment]
It seems like we'll want to wait for these fixes before releasing 0.29

**Comment by eliben** [comment]
That's OK. pyelftools is fairly low-level infra and not aiming for a stable API. I wouldn't break things just for fun, but if there's a good reason to do so, that's not a big problem.

**Comment by sevaa** [comment]
Catch #418. I'll keep ranges until the next one.

**Comment by rdunklau** [comment]
Thanks ! I'm closing this.

**Comment by sevaa** [comment]
Make a new issue.
