### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by eliben** [eliben/pyelftools#415]
It's really time...

While at it, drop support for all older versions of 3.x which aren't supported any more at https://www.python.org/downloads/

**Comment by eliben** [comment]
The soon-to-come 0.29 release will be the last one to support Python 2. Once that release is out I'll start working on removing Python 2 support from the code-base.

**Comment by ltfish** [comment]
Amazing! We have been waiting for this for a long time!

**Comment by eliben** [comment]
> Amazing! We have been waiting for this for a long time!

Can you share a bit more about why you've been waiting for this?

**Comment by ltfish** [comment]
Both angr and CLE heavily rely on pyelftools for loading ELF files. We (or I personally) have some plan to profile pyelftools and increase its speed (especially for loading large files with DWARF information), but the fact that it's not fully Python-3-compatible makes us hesitant.

An added benefit is that we can get rid of a few compatibility hacks (e.g., bytes vs str) that we have in CLE.

**Comment by eliben** [comment]
0.29 has just been released

The plan for 0.30 would be to sunset Python 2 support. I will wait for a few days to see that all is clear with 0.29 and folks don't complain about blocking issues, and will then do the Python 2 removal early - this will make submitting PRs to the repo easier as well.

**Comment by rupran** [comment]
Is there anything I (or the other active folks) can do to help with this task or do you already have a master plan?

**Comment by eliben** [comment]
@rupran thanks for the offer, but it's fairly simple - the main thing would be to drop the requirements and testing, to make it easier to submit future changes. I'll take care of it this week
