### ISSUE TITLE
Release v0.29

### ISSUE THREAD

**Issue by eliben** [eliben/pyelftools#421]
I'm planning to release pyelftools v0.29 by tagging it and sending a version to PyPI.

**Comment by sevaa** [comment]
Can we stuff the elements of that clang-11 binary under the release? So far, I see a handful of new forms and operators. Shouldn't take long.

**Comment by eliben** [comment]
> Can we stuff the elements of that clang-11 binary under the release? So far, I see a handful of new forms and operators. Shouldn't take long.

Sure, there's no rush.

> 
> I then wanted to do a housekeeping PR about the sample binaries - reduce the clutter. This will make the CI run faster, for one thing. That can be done after the release.

Sounds like a good plan. I will defer the Python 2 purge to after 0.29 as well

**Comment by sevaa** [comment]
A bit of trouble in paradise. Readelf 2.38 dumps quite a few DIEs of my clang-11 binary, then bails with an error code and the following message:

> readelf: Warning: DIE at offset 0xc875 refers to abbreviation number 2915 which does not exist

I can tell that the parsing process went off the rails long before that; for one thing, the DIE nesting level in the output goes into negatives after a while. But that means the autotest is broken, too.

Can you build, instead of 2.38, the *latest* binutils? Maybe they've fixed that. If not, I have a working environment for debugging binutils, I could try and patch whatever's going on. Feels like cheating, but it won't be the first time.

**Comment by eliben** [comment]
Sure, here's a readelf built from the master branch: https://www.dropbox.com/s/69lm3e7zgg7d7u1/readelf-master?dl=0

If it doesn't help, maybe binutils simply hasn't caught up with the newest DWARF v5 yet... :shrug:

**Comment by sevaa** [comment]
Still a bunch of "offset is too great" warnings, but no error exit. Guess we'll use this one.

**Comment by eliben** [comment]
What's special about that binary? Could it be that the compiler is generating something fishy?

If this is clang-generated, it may be interesting to dump it using `llvm-dwarfdump` to see if it also gets confused.

**Comment by sevaa** [comment]
Can't tell yet if the binary is fishy or GNU readelf is off. For all we kno, could be the latter.

**Comment by sevaa** [comment]
Update: readelf is definitely to blame. I'll try submitting patches this time.

**Comment by eliben** [comment]
Back from vacation.

Is there anything else blocking this release? The new support does not have to be final...

I'd like to release 0.29 and start removing Python 2 support, since this will make working with the code easier for everyone.

**Comment by rdunklau** [comment]
Hello, 

I'm back from vacation too. I'd like to get #426 in shape. It's not blocking, so no big deal if it doesn't make it through this release though.

**Comment by eliben** [comment]
> I'm back from vacation too. I'd like to get #426 in shape. It's not blocking, so no big deal if it doesn't make it through this release though.

Thanks for the update, @rdunklau 

Waiting for @sevaa to get back so we can make a decision on this

**Comment by sevaa** [comment]
I asked a question on that PR. Waiting for @rdunklau to anwer.

**Comment by eliben** [comment]
@sevaa if @rdunklau thinks that whole PR can wait for the next release, do you still consider it blocking?

**Comment by sevaa** [comment]
Not really. But @vsoch wanted that functionality too.

**Comment by pimvullers** [comment]
What about #349, which is also marked as blocking next release?
Has this been resolved? Missing files in a (pypi?) package should be doable to fix for 0.29 as well.

**Comment by eliben** [comment]
Yes, that's also in scope (which is why it's marked blocking). PRs for that issue are welcome.

**Comment by sevaa** [comment]
There is a test file of type .dat, which is not mentioned in manifest. I can provide a PR for that, but won't know how to test that.

**Comment by eliben** [comment]
Python's packaging has always been painful. What I did in the past was take the generated tarball, use a clean virtual env to set it up and run all tests in it. Typically test files needed for the tests would have to be in the manifest, otherwise they would not be included in the tarball and the tests would fail.

**Comment by eliben** [comment]
... apparently these days you don't even need MANIFEST anymore - https://www.remarkablyrestrained.com/python-setuptools-manifest-in/

**Comment by eliben** [comment]
Anyway, @sevaa if you want to reproduce the current issue with the released 0.28, you can follow these steps:

1. Create a fresh virtualenv, e.g. `python3 -mvenv <some-venv-path>`
2. Activate it
3. Download the 0.28 source tarball from PyPI https://pypi.org/project/pyelftools/#files
4. Untar this tarball and cd into the resulting dir
5. Run pyelftools tests in this directory using your activated venv python

You'll see the failures due to failing to find `.dat` files; we need to add `.dat` files to MANIFEST.in for that not to happen, or use this new `setuptools_scm` thing (but maybe the former will be easier since it just worked for pyelftools for many years)

**Comment by sevaa** [comment]
But there is no way to run a test **for the proposed fix** until the next version is published to pypi, is there?

**Comment by eliben** [comment]
> But there is no way to run a test **for the proposed fix** until the next version is published to pypi, is there?

Yes, there is. You have to run `python setup` with the `sdist` flag, which creates a new source distribution tarball for you and you can test that. See the "preparing new release" notice in https://github.com/eliben/pyelftools/blob/master/TODO

FWIW I can do all this when preparing the 0.29 release; we just need to sort out the remaining supplemental info PR. I'll appreciate help in testing things, though, before I push to PyPI.

**Comment by sevaa** [comment]
Okay, here is #433 . The dat files are in the tarball, I've checked.

**Comment by eliben** [comment]
[pyelftools-0.29.tar.gz](https://github.com/eliben/pyelftools/files/9296236/pyelftools-0.29.tar.gz)

Here's the release candidate tarball for 0.29, please help me test it before I push to PyPI! I haven't tagged in Git yet, so this is provisional version. To test it, follow the instructions in https://github.com/eliben/pyelftools/issues/421#issuecomment-1205237339 except download the tarball from here and not PyPI.

P.S. This file is much larger than before because LLVM binaries are so damn big, and we carry `llvm-dwarfdump` for testing now, *sigh*.

@sevaa @rupran

**Comment by rupran** [comment]
Looks good from my side, running the tests from the downloaded tarball and using the installed version from my tools works fine.

**Comment by sevaa** [comment]
Followed the instruction in that comment over there, running on Debian Buster, success on all tests.

I'll do something about the LLVM binaries.

**Comment by eliben** [comment]
> Followed the instruction in that comment over there, running on Debian Buster, success on all tests.
>
Thank you both for testing 👍 
 
> I'll do something about the LLVM binaries.

From my past experience with LLVM, this is just the way things are - LLVM binaries are huge.

I was going back and forth about how big a problem this is. I'd think these days most folks who install the package do so from the wheel which doesn't include the tests and is very small. The source tarball is probably used in much more special scenarios (maybe building on various Linux distributions' package managers), and 15 MiB there isn't the end of the world (this is 2022 after all). I was considering whether to include these binaries and tests at all - pyelftools gets tested all the time in CI after all. Eventually I concluded that the easiest thing will just be to do what it's always done and absorb the size increase.

**Comment by eliben** [comment]
I've tagged 0.29 and pushed to PyPI

https://github.com/eliben/pyelftools/releases/tag/v0.29

Thanks everyone for the help testing and the contributions
