### ISSUE TITLE
debug_ranges_sec and debug_rnglists_sec are not mutually exclusive.

### ISSUE THREAD

**Issue by rdunklau** [eliben/pyelftools#424]
Hello,

I've just tested the range list implementation for dwarfv5, and I'm not sure it's the right way to approach it. In the same ELFFile, we can have compile units in DWARF version 5, and other in version 4. Each of those will reference their respective .debug_rnglists and .debug_ranges sections. I guess it can also happen with location lists ?

As for how to produce such a binary, I suspect that having different compile options for different compilation units which are then all linked together will produce that. I don't know how often it happens in real life though.

**Comment by sevaa** [comment]
If you manage produce a binary like that, let me know. It'd be a fun test case. I won't be surprised, however, if readelf, our reference implementation of choice, won't handle that either.

**Comment by sevaa** [comment]
A binary would be good.

**Comment by sevaa** [comment]
I'll roll the fix for that into the loclists/rnglists redesign I'm currently on. It's a surprisingly cheap change.

**Comment by rdunklau** [comment]
In terms of API, it would probably make sense to have the location_list / range_list API at the CompileUnit level, don't you think ?
And maybe keep the existing ones with an optional dwarf_version parameter if we want to be explicit while staying backwards-compatible.
For the binary, I'll open a PR with it.

**Comment by eliben** [comment]
Can this be closed after #429 landed?

**Comment by rdunklau** [comment]
I think we can, thanks !
