### ISSUE TITLE
Should we even rely on readelf as the reference implementation for DWARF parsing?

### ISSUE THREAD

**Issue by sevaa** [eliben/pyelftools#427]
DWARF5 is 5 years old now. The people behind readelf don't even try to keep up until pushed. Looking at its output as some kind of ideal reference implementation doesn't seem sensible anymore. Maybe we should split the readelf autotests into two parts - ones that test the parsing of ELF proper, and the DWARF parsing, and use another DWARF tool as a reference implementation - e. g. dwarfdump, or llvm-dwarfdump.

OBTW, for the supporting sections of DWARF (ones other than `debug_info`), dumping the whole section is not even the dominant use case outside of readelf-like tools. Debugger type applications don't scan/parse those _en masse_, they follow the references in DIEs. Most of the time, the records in those sections make no sense outside of the DIE that references them anyway. Currently, I'm engaged in a discussion with a gentleman from the GNU coalition, as to what should be the format of the loclist dump - should it be DIE-aware or not. The PC ranges in loclists and rnglists are relative to the starting PC of the current CU, and there is no way to know that short of looking into debug_info. Once you add the offset in the loclist to the base PC, it makes sense and lets one know where the variable is for a given execution spot, but from the readelf creator's standpoint, you are no longer dumping the loclists section _alone_. In light of this discussion, treating readelf as the source of the ultimate truth becomes even more ridiculous.

**Comment by eliben** [comment]
TL,DR: I'm not opposed to the idea, though it will take some planning and work.

`readelf` tests have served pyelftools very well and have been, on the balance, hugely valuable. This is the kind of deep testing that I like - you add a single new binary and your code gets exercised *really* well to compare to an existing tool. 

That said, in the past we never had an issue of _running ahead_ of `readelf` on DWARF support, so this seems like fundamentally new data. If this is indeed the case, and if we know that other tools are much better at keeping up-to-date, I think it could work if we had another set of comparison tests for more advanced DWARFv5 features.

This will require some planning and work, of course, but I don't see why it can't be done.

**Comment by eliben** [comment]
Like, there could be a wholly different test runner called, say `run_dwarfdump_tests.py`, with its own set of test binaries to compare. It would only focus on specific DWARF dumping tasks, but it would still mean we'd need to implement a reasonably featured dumper using pyelftools that would emit the data in a format comparable to the new external tool.

**Comment by sevaa** [comment]
That was the vague outline of my plan :) That said, I'd have to take a careful look at dwarfdump and see what does their support for DWARF5 look like. It's a different team from GNU binutils.

**Comment by eliben** [comment]
Does it worry you that it's also a tool from the same repo? I wonder if llvm-dwarfdump would be better maintained at this point.

**Comment by sevaa** [comment]
What's the relationship between the two? Is llvm-dwarfdump a fork? I can try that one.

**Comment by eliben** [comment]
`llvm-dwarfdump` is its own thing, part of the LLVM toolchain. It's been around for a long time, from the very early days of LLVM. I asked around and was told that it's pretty up-to-date with modern DWARFv5 stuff, so probably worth looking at.

**Comment by sevaa** [comment]
For one thing, it has separate dump options for debug_ranges and debug_rnglists.

I'm afraid a lot of stuff from descriptions.py will have to be somewhat duplicated. Descriptions existed all this time mostly to generate readelf-like strings, but it's a part of the library and its API now.

I've tried with llvm v11, at least it doesn't choke on my current binary. If you don't mind, I'll stash my current changes and try and implement a test against dwarfdump in a brand new PR with the current master, see where it takes me.

**Comment by eliben** [comment]
True, descriptions are there mostly for readelf and I don't really consider them a necessarily stable part of the API. That said, we'll still keep the readelf tests, so yes there will be some duplication, though it's possible that a lot can be reused.

Plan SGTM

**Comment by sevaa** [comment]
Capital, now llvm-dwarfdump is giving me errors on a test binary :(
