### ISSUE TITLE
debug info from external file?

### ISSUE THREAD

**Issue by vsoch** [eliben/pyelftools#432]
Heyo! I'm wondering if pyelftools has support for being able to get external debug, e.g., if I have a container with libc and debug info separately (e.g., I apt-get installed it, and it's under debug) is pyelftools able to read the separate debug? Thanks!

**Comment by sevaa** [comment]
Isn't PR #426 what you need?

**Comment by vsoch** [comment]
Yes that's just it! Apologies I didn't search PRs, only issues. I'll follow there!
