### ISSUE TITLE
is dwarf_decode_address.py suite for dwarf version 5 ?

### ISSUE THREAD

**Issue by DogeWatch** [eliben/pyelftools#461]
https://github.com/eliben/pyelftools/blob/master/examples/dwarf_decode_address.py#L91
I found `filename = lineprog['file_entry'][prevstate.file - 1].name` should change to `filename = lineprog['file_entry'][prevstate.file].name` to parse the dwarf version 5 file.

**Comment by eliben** [comment]
Is this fixed by #463 and should be closed?

**Comment by eliben** [comment]
Closing. Reopen if needed, explaining why #463 is not a fix
