### ISSUE TITLE
elf writer

### ISSUE THREAD

**Issue by dsula** [eliben/pyelftools#462]
I have to read an elf, then modify it (adding some sections) and then write it out.
Looking at the API, I don't think pyelftools has that capability. But I wanted to confirm. Maybe I'm mistaken.
Thank you.

**Comment by sevaa** [comment]
ELF writing capabilities were never in pyelftools, and were never planned.

**Comment by dsula** [comment]
Ok, thank you for confirming. That's unfortunate.
