### ISSUE TITLE
"The pyelftools library provided has no write support"

### ISSUE THREAD

**Issue by adurtydog** [eliben/pyelftools#464]
Hi
Having installed the pyelftools library via "pip install pyelftools" i get the error below when running a comand.

"This tool requires version of pyelftools with ELF write support.
Get it from https://github.com/mefistotelis/pyelftools.git"

I then downloaded the master-zip file and re installed  via "setup.py install" but get the same error

**Comment by sevaa** [comment]
That's more of a general Python problem - how does one install a fork of a module on top of its original? Try uninstalling pyelftools altogether, and then installing the writing fork.

**Comment by mefistotelis** [comment]
if you're trying to use `dji-firmware-tools`, the scripts there do:
```
sys.path.insert(0, '../pyelftools')
```

at stat. In other words, put `pyelftools` folder in the same place where `dji-firmware-tools` folder is, and it will work. no need to install it (though if installed properly, it will also work).
