### ISSUE TITLE
Example of getting DW_LNCT_MD5

### ISSUE THREAD

**Issue by ewanoughton** [eliben/pyelftools#474]
Apologies in advance - been poking around the varied DWARF info examples in the debugger to no avail. 

I seemingly have clang emitting DWARFv5 info in the elf, which should include MD5 checksums of the compiled source.  Can you please point me at an example of grabbing this info with pyelftools? 

Thanks

Ewan

**Comment by sevaa** [comment]
See https://github.com/eliben/pyelftools/blob/master/test/test_dwarf_formdata16.py

**Comment by ewanoughton** [comment]
Much appreciated, thanks!
