### ISSUE TITLE
Wiki Links are Broken

### ISSUE THREAD

**Issue by reynoldsbd** [eliben/pyelftools#480]
The "user's guide" links in README.rst seem to be broken. They are pointing to a GitHub wiki, but it looks like this repo does not have a wiki enabled (at least, it isn't visible to me). Is there some other source of documentation I can refer to?

**Comment by eliben** [comment]
Thanks for flagging this; it should be restored now.

**Comment by reynoldsbd** [comment]
Thank you!!
