### ISSUE TITLE
Cortex M33 elf binary error: no decoding mapping for 46 [tag] 

### ISSUE THREAD

**Issue by KShingala** [eliben/pyelftools#484]
I am trying to use angr to generate control flow graph for CM33 binary but get this error from elftool from backend_z3.py.

I am using the following in my script to 

<code>
arch = archinfo.ArchARM(archinfo.Endness.LE)
p = angr.Project('my_binary.elf', arch=arch)
</code>

Can someone help me what I am doing wrong?

**Comment by sevaa** [comment]
Tag 0x46 is `DW_TAG_dynamic_type`. It's documented in DWARFv5, but for some reason not listed in the tag enum pyelftools. It's a fairly simple fix on our side, but who knows when will the current state of the master branch get released. I'll do a PR.

**Comment by KShingala** [comment]
Here are the file I used to experience the error. [](url)
[example.zip](https://github.com/eliben/pyelftools/files/12409594/example.zip)

**Comment by sevaa** [comment]
Reproduced. This is not about a DWARF tag 0x46, like I thought, the error is taking place while parsing the `.ARM.attributes` section, and the enum that is lacking 46 (decimal) is `ENUM_ATTR_TAG_ARM` under elf/enums.py.

Now I need to find an authoritative reference on those, figure out what does 46 stand for, and how does one parse the rest of the attribute record...

**Comment by KShingala** [comment]
I dont mind using the binary as an autotest, please feel free to use it as you like.

**Comment by sevaa** [comment]
Either way, the fix seems to be a new enum value - but in a different enum. See the changeset in #491, and see if you can apply that.
