### ISSUE TITLE
ELF write support?

### ISSUE THREAD

**Issue by shirok1** [eliben/pyelftools#498]
Here is a fork that imply this: https://github.com/mefistotelis/pyelftools

It is mainly used in https://github.com/o-gs/dji-firmware-tools, to imply ELF generation for analysed binary.

I wonder if this could be merged into upstream.

cc @mefistotelis

**Comment by mefistotelis** [comment]
This was discussed way back in #15.
Though maybe something changed since then.

**Comment by eliben** [comment]
Indeed, this was discussed in #15 and nothing changed from my point of view. This remains outside the scope of pyelftools; feel free to use the linked fork if it works for you.
