### ISSUE TITLE
Problem in Evaluating Dwarf Location Expression

### ISSUE THREAD

**Issue by sivakrishna523** [eliben/pyelftools#50]
Hi,
  I want to evaluate the DW_AT_Location attribute.
So, first I intialiazed Compile unit and then I instantiated GenericExprVisitor object and then using that reference, calling process_expr(value) procedure. But it is retuning 'none' every time.

Code flow is as follows

Get CU instance
Gref = GenericExprVisitor(CU.structs)
x, d = die.attributes.items()
if x == 'DW_AT_Location'
Gref.process_expr(d.value)

**Comment by eliben** [comment]
Do you have a special problematic input file this happens in?

**Comment by sethml** [comment]
Possibly fixed by pull request #89? Give it a try...

**Comment by eliben** [comment]
Reopen if the fix suggested by @sethml didn't work
