### ISSUE TITLE
Error while parsing Microchip ELF

### ISSUE THREAD

**Issue by olimexsmart** [eliben/pyelftools#518]
Hi, I'm trying to use the library with the ELF file generated by the Microchip xc16 compiler. 

For example the `examine_dwarf_info.py` preview crashes with
```
  File "C:\Python311\Lib\site-packages\elftools\dwarf\structs.py", line 106, in __new__
    assert address_size == 8 or address_size == 4, str(address_size)
```
In general also the out-of-the-box `readelf` has some trouble with it, the only tool I've seen working is the one bundle along side the compiler: `xc16-readelf`

Any suggestion in general? Thanks
[test.elf.pdf](https://github.com/eliben/pyelftools/files/13312010/test.elf.pdf)

Edit: GitHub won't let me upload ELF file, so I appended "pdf" to the name

**Comment by sevaa** [comment]
Somewhat known issue, see #473.  XC16 emits a highly unusual flavor of DWARF, definitely not compliant with the standard.

**Comment by olimexsmart** [comment]
Thanks for the quick response, sorry for the double posting but a couple hours of googling didn't find the mentioned issue

Sadly, I think we are about to confront ourselves with some typical corporate nonsense, all their documentation (starting from the datasheet) mention as being compliant with the DWARF2 standard. ([here](https://onlinedocs.microchip.com/pr/GUID-ECD8A826-B1DA-44FC-BE0B-5A53418A47BD-en-US-12/index.html?GUID-73AA183F-4E27-454F-8EA8-F31DCBBAB54B) and [here, for example](https://onlinedocs.microchip.com/oxy/GUID-91118B1F-52AE-4822-A75E-B65FA4C48896-en-US-1/GUID-005D6176-CB36-40B0-9936-F06172D05CC3.html))

Will try to pull some strings with a internal contact at Microchip and let you know

**Comment by davea42** [comment]
Well, .debug_aranges and .debug_frame and .debug_info
and .debug_pubnames  have non-standard content and are unreadable with libdwarf.
libdwarf was first written for DWARF2 and still correctly reads any standard version of DWARF.

.debug_str is formally standard (it is hard  to make a .debug_str that is not standard-conformant)
but the content is a series of one -letter or empty strings.  Very odd.

libdwarf is not going to attempt to read such stuff either.

David Anderson, maintainer of libdwarf.

**Comment by sevaa** [comment]
@davea42 : just read the linked issue. It's DWARF, Jim, but not as know it.

**Comment by davea42** [comment]
Yes. Should have read the link.  Sorry.  But  calling it DWARF2 is just wrong.
Calling it a unique debug format based on DWARF2 might be accurate.

**Comment by sevaa** [comment]
This structure starts making a bit of sense if you assume that the logical byte is 16 bits. That said, with normal DWARF datatypes, that would make for a file where every other (physical) byte is zero, but that's not the case.

**Comment by sevaa** [comment]
Simply throwing away odd bytes in the DWARF sections makes for a passable parser :) In this issue's binary, there are no odd nonzero bytes. So with the following monkeypatch, pyelftools works:

```
from io import BytesIO
from elftools.elf.elffile import ELFFile
from elftools.elf.relocation import RelocationHandler
from elftools.dwarf.dwarfinfo import DWARFInfo, DebugSectionDescriptor

def _read_dwarf_section_even(self, section, relocate_dwarf_sections):
    """ Read the contents of a DWARF section from the stream and return a
        DebugSectionDescriptor. Apply relocations if asked to.
    """
    # The section data is read into a new stream, for processing
    section_stream = BytesIO()
    section_stream.write(section.data()[::2]) ######## Even bytes only!

    if relocate_dwarf_sections:
        reloc_handler = RelocationHandler(self)
        reloc_section = reloc_handler.find_relocations_for_section(section)
        assert(reloc_section is None)
        #if reloc_section is not None:
        #    reloc_handler.apply_section_relocations(
        #            section_stream, reloc_section)

    return DebugSectionDescriptor(
            stream=section_stream,
            name=section.name,
            global_offset=section['sh_offset'],
            size=section.data_size//2,      ############## Size effectively one half!
            address=section['sh_addr'])

# Main

ELFFile._read_dwarf_section = _read_dwarf_section_even

with open("E:\\Seva\\Projects\\dwex\\samples_todo\\XC16\\LNET_MCLV2_dsPIC33CK256MP508.production.elf", "rb") as f:
    e = ELFFile(f)
    di = e.get_dwarf_info()
    # Do what you want to that DWARFInfo
```
There is no DWARF relocation in this binary, so I threw the relocation logic away. Can't sensibly debug those.

**Comment by olimexsmart** [comment]
@sevaa I think you got it right, you can find attached a PDF, the TLDR is the following (from the last page):

> To decode the data from our DWARF sections when compiled for PIC24, dsPIC30F, or dsPIC33C/E/F devices; skip
every other byte

and 

> If an external tool is used to interpret DWARF debugging information created by the XC16 and/or XC-DSC
compilers, the EF_PIC30_NO_PHANTOM_BYTE flag can be used to determine if phantom bytes in DWARF
sections must be recognized and discarded.

[MPLAB XC16 and XC-DSC DWARF Differences.pdf](https://github.com/eliben/pyelftools/files/13351429/MPLAB.XC16.and.XC-DSC.DWARF.Differences.pdf)

**Comment by sevaa** [comment]
@olimexsmart good find. The linked guide quietly assumes that no other compiler will ever generate code for PIC devices, or if it does, it will respect the EF_PIC30_NO_PHANTOM_BYTE bit in the E_FLAGS. Oh well, that's all we've got anyway.

**Comment by olimexsmart** [comment]
> The linked guide quietly assumes that no other compiler will ever generate code for PIC devices, or if it does, it will respect the EF_PIC30_NO_PHANTOM_BYTE bit in the E_FLAGS.

The thing with embedded programming is that everyone kinda builds its stuff on its lonely island and doesn't expect much interaction with the outside world and this kind of things happens all the time sadly.

I'm really not familiar with the relocations concept, will try anyway to ask my contact, but I would not expect anything more, since this document already was sent to me in a "that's all we got" kinda mood

Thanks for the support, I briefly tested your path and seems to work ok

**Comment by sevaa** [comment]
https://en.wikipedia.org/wiki/Relocation_(computing)

Some CPU vendors (notably MIPS) go to great lengths to prevent the need for relocations in their binaries. Don't know about what PIC does to that effect.

In theory, an ELF file may contain relocation instructions that point into the DWARF sections. If you are trying to debug a running process where your binary is not loaded at its preferred address, all the absolute addresses in the DWARF data (code locations, data locations) need to be relocated to accommodate the different starting address.

The primary use case of `pyelftools`, however, seems to be parsing DWARF from a binary at rest. In this scenario, the process of relocation can be safely omitted, since the binary is not technically loaded (that is, not loaded *by the OS, for execution*), so the notion of its starting address is not applicable.

Whether to apply the relocation entries or not is an optional, True by default flag in the `ELFFile` constructor.

---

If the patch works, close the issue.

**Comment by olimexsmart** [comment]
I think that in this case we are falling in the the following case described by the wikipedia article:

>Prior to the advent of multiprocess systems, and still in many embedded systems, the addresses for objects were [absolute](https://en.wikipedia.org/wiki/Absolute_address) starting at a known location, often zero

**Comment by sevaa** [comment]
>the addresses for objects were absolute

Could be.

Anyway, were we to roll this into pyelftools proper, can you please compile a "Hello world" type program with XC16 for us to serve as a unit test, and share the binary?

**Comment by sevaa** [comment]
I expected a smaller test binary, but I guess it's an OS-less environment and every binary would kind of carry its own OS. This will work, thanks. Didn't need the whole project tree though, just the ELF file.

What about DWARF section compression, which is done with `-gz=zlib` in the compiler options? I wonder if decompression should be applied before or after stripping the odd bytes.

**Comment by olimexsmart** [comment]
I think it is the latter case:
```
olli@olligram:~$ /opt/microchip/xc16/v2.10/bin/xc16-gcc -gz=zlib  testXC16.c
elf-cc1: error: unrecognised debug output level "z=zlib"
```
Let me know if you need some other insights no problem

**Comment by sevaa** [comment]
This will do, thank you. If a binary with compressed sections ever surfaces, we'll revisit this. For the time being, I'll leave a comment.

**Comment by sevaa** [comment]
The PR has landed. Is this enough to close the issue?
