### ISSUE TITLE
Don't use Unlicense

### ISSUE THREAD

**Issue by rossburton** [eliben/pyelftools#524]
Please consider moving away from the Unlicense license to something more conventional and respected.

A good summary of the issues: https://chrismorgan.info/blog/unlicense/. Primary issues are that distributions are starting to refuse to package "public domain" code (including CC0/Unlicense) and the unlicense web site doesn't work anymore.

A good alternative would be the BSD-0 or MIT-0 licenses.

**Comment by eliben** [comment]
GitHub supports the Unlicense as a valid license type. It's listed here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

It's also listed here: https://choosealicense.com/appendix/

It's also in the dropdown when you create a new GitHub repo:

![Screenshot 2023-12-06 at 06-42-59 Build software better together](https://github.com/eliben/pyelftools/assets/1130906/b3929886-60b9-4262-ac60-c4b1dc134d94)

[According to Wikipedia](https://en.wikipedia.org/wiki/Public-domain-equivalent_license) the Unlicense is approved by OSI.

So it works for me at this time.

----

P.S. I've never heard of BSD-0, MIT-0 and don't see them listed in any of the places I mentioned above.

**Comment by rossburton** [comment]
Sorry, I meant MIT.

Just because a license is known by GitHub doesn't make it a _good_ license.
