### ISSUE TITLE
Add support for aarch64 PAC/BTI markers

### ISSUE THREAD

**Issue by rossburton** [eliben/pyelftools#526]
The `.note.gnu.property` segment will contain GNU_PROPERTY_AARCH64_FEATURE_1_BTI and GNU_PROPERTY_AARCH64_FEATURE_1_PAC markers if the code is compiled with BTI/PAC enabled.

readelf can dump these:

```
$ readelf -n .../libacl.so

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_PROPERTY_TYPE_0
      Properties: AArch64 feature: BTI, PAC
```

But pyelftools doesn't know how to parse the data.

**Comment by sevaa** [comment]
Thanks for letting know. If you feel up to it, submit a PR. If not, please share a minimal binary with those properties, and someone will get to it (eventually).

**Comment by rossburton** [comment]
Here's a representative library:

[libattr.so.1.1.2501.zip](https://github.com/eliben/pyelftools/files/13602338/libattr.so.1.1.2501.zip)

I have most of a patch locally that I've been using and just needs a test case, but due to !524 I can't submit it.

**Comment by rossburton** [comment]
So it looks like GitHub doesn't mail when issues are mentioned in PRs, so i didn't notice that PR at all!

```
$ python3 ./scripts/readelf.py  /yocto/ross/build/tmp/sysroots-components/cortexa57/libice/usr/lib/libICE.so -n

Displaying notes found in: .note.gnu.property
  Owner                Data size        Description
  GNU                  0x00000010	NT_GNU_PROPERTY_TYPE_0 (program properties)
      Properties: aarch64 feature: bti, pac
```

That will do nicely, thanks.
