### ISSUE TITLE
Missing DT_MIPS_XHASH

### ISSUE THREAD

**Issue by rossburton** [eliben/pyelftools#569]
`ENUM_D_TAG_COMMON` is missing an entry for `DT_MIPS_XHASH`.  For reasons best known to the binutils maintainers this isn't defined in the common `elf.h` but is defined and used in `elf.c` (and present in compiled MIPS binaries):

```
bfd/elf.c:#define DT_MIPS_XHASH          0x70000036
```

https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=bfd/elf.c;h=7d3d2063130bd3d5bd988207ca68b15f76ac85c8;hb=HEAD#l1760

LLVM has the same definition:
```
llvm/include/llvm/BinaryFormat/DynamicTags.def:MIPS_DYNAMIC_TAG(MIPS_XHASH, 0x70000036)        // GNU-style hash table with xlat.
```

**Comment by sevaa** [comment]
@rossburton This was addressed.

**Comment by eliben** [comment]
If this is fixed by https://github.com/eliben/pyelftools/pull/571, the issue can be closed
