### ISSUE TITLE
Arm abbrev_code

### ISSUE THREAD

**Issue by claude80** [eliben/pyelftools#57]
Hi

it seems that with arm binary the abbrev_code is wrong, pyelftools catchs only the last byte, the abbrev_code is on 2 bytes.

ex:
 <1><6a126>: Abbrev Number: 6 (DW_TAG_typedef)

DW_TAG_typedef is 0x16

Cheers,

**Comment by eliben** [comment]
Closing since there's been no reply after more than 2 years
