### ISSUE TITLE
Helper to check type in ELFFile.get_section_by_name()?

### ISSUE THREAD

**Issue by rossburton** [eliben/pyelftools#570]
When a library with debug symbols is split into code and debug info, the debug info has all of the original segments but without any content.  This means that if you do `get_section_by_name(".dynamic")` you'll get a stub `Section` instance.

For code which wants to poke around an ELF, I wonder if it would be useful to have an optional arguments to save boilerplate. Maybe:

```
# Check the type is as expected
def get_section_by_name(self, name, type=None)
...
get_section_by_name(".dynamic", "SHT_DYNAMIC")
```

Or:

```
# Check the type isn't NOBITS
def get_section_by_name(self, name, content_only=False)
get_section_by_name(".dynamic", True)
```

**Comment by sevaa** [comment]
@eliben
I don't know, an optional argument it will save the OP a one line check...

**Comment by eliben** [comment]
@rossburton can you elaborate a bit more on the boilerplate saved?

**Comment by rossburton** [comment]
It _is_ pretty minimal, but I've a lot of code that does this:

```
dynamic = elf.get_section_by_name('.dynamic')
if not dynamic or dynamic["sh_type"] != "SHT_DYNAMIC":
  return
```

I can have a convenience wrapper in my code if you prefer.

**Comment by eliben** [comment]
Understood, thanks. I'd like to keep it minimal for now; will be on the lookout for similar requests
