### ISSUE TITLE
Parsing with DWARF v5 fails

### ISSUE THREAD

**Issue by benediktibk** [eliben/pyelftools#588]
In zephyr pyelftools is used to parse the generated binaries. There is a flag which forces gcc to produce only DWARF v4, as unfortunately parsing fails with DWARF v5. An example of such an error can be found here:

https://github.com/zephyrproject-rtos/zephyr/actions/runs/12369159520/job/34521122341?pr=83083

The ELF binary was generated with this command:

    gcc
    -m32
    zephyr/CMakeFiles/zephyr_final.dir/misc/empty_file.c.obj
    -o
    zephyr/zephyr.elf
    zephyr/CMakeFiles/offsets.dir/./arch/x86/core/offsets/offsets.c.obj
    zephyr/arch/arch/x86/staticIdt.o
    zephyr/arch/arch/x86/irq_int_vector_map.o
    zephyr/arch/arch/x86/irq_vectors_alloc.o
    zephyr/arch/arch/x86/gdt.o
    zephyr/arch/arch/x86/pagetables.o
    -T
    zephyr/linker.cmd
    -Wl,-Map=.../Development/zephyr_playground/build/zephyr/zephyr_final.map
    -Wl,--whole-archive
    app/libapp.a
    zephyr/libzephyr.a
    zephyr/arch/arch/x86/core/libarch__x86__core.a
    zephyr/lib/libc/picolibc/liblib__libc__picolibc.a
    zephyr/lib/libc/common/liblib__libc__common.a
    zephyr/subsys/random/libsubsys__random.a
    zephyr/drivers/interrupt_controller/libdrivers__interrupt_controller.a
    zephyr/drivers/console/libdrivers__console.a
    zephyr/drivers/serial/libdrivers__serial.a
    zephyr/drivers/timer/libdrivers__timer.a
    -Wl,--no-whole-archive
    zephyr/kernel/libkernel.a
    -L.../Development/zephyr_playground/build/zephyr
    -Wl,--print-memory-usage
    -m32
    -msoft-float
    -fuse-ld=bfd
    -Wl,--gc-sections
    -Wl,--build-id=none
    -Wl,--sort-common=descending
    -Wl,--sort-section=alignment
    -Wl,-u,_OffsetAbsSyms
    -Wl,-u,_ConfigAbsSyms
    -nostdlib
    -static
    -Wl,-X
    -Wl,-N
    -Wl,--orphan-handling=warn
    -Wl,-no-pie
    -specs=picolibc.specs
    -DPICOLIBC_LONG_LONG_PRINTF_SCANF
    -L".../zephyr-sdk-0.17.0/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/12.2.0/32/soft-float"
    -lc
    -lgcc

Traceback of the failure:

    Traceback (most recent call last):
      File "/home/benedikt/Development/zephyr_playground/zephyr/scripts/logging/dictionary/database_gen.py", line 589, in <module>
        main()
      File "/home/benedikt/Development/zephyr_playground/zephyr/scripts/logging/dictionary/database_gen.py", line 557, in main
        string_mappings = extract_static_strings(elf, database, section_extraction)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/benedikt/Development/zephyr_playground/zephyr/scripts/logging/dictionary/database_gen.py", line 467, in extract_static_strings
        str_vars = extract_string_variables(elf)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/benedikt/Development/zephyr_playground/zephyr/scripts/logging/dictionary/database_gen.py", line 369, in extract_string_variables
        loc = loc_parser.parse_from_attribute(loc_attr, die.cu['version'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/benedikt/Development/zephyr_playground/.venv/lib/python3.12/site-packages/elftools/dwarf/locationlists.py", line 309, in parse_from_attribute
        return self.location_lists.get_location_list_at_offset(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/benedikt/Development/zephyr_playground/.venv/lib/python3.12/site-packages/elftools/dwarf/locationlists.py", line 96, in get_location_list_at_offset
        raise DWARFError("For this binary, \"die\" needs to be provided")              
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    elftools.common.exceptions.DWARFError: For this binary, "die" needs to be provided

I was not able to reproduce this error with readelf.py only, but as everything is fine with DWARF v4 I assume the usage of the python library should be correct.
The binary which triggers the error can be found here: http://downloads.benediktschmidt.at/zephyr.zip

Might this be related to #581?

**Comment by benediktibk** [comment]
I almost forgot:

    $ pip list | grep pyelftools
    pyelftools          0.31

**Comment by sevaa** [comment]
It looks like the location list in question has entries of type `DW_LLE_base_addressx`/`DW_LLE_startx_endx`. In order to decode those, the parser needs to take a look at the top DIE of the compilation unit where the reference to the loclist was found. Those entry types were indeed introduced in DWARFv5. To make this error go away, pass the optional `die` parameter to `LocationParser.parse_from_attribute()`. In other words, line 369 in `database_gen.py` should go:
```
loc = loc_parser.parse_from_attribute(loc_attr, die.cu['version'], die)
```
We know the API is a bit clumsy and providing the DIE reference implicitly lets the library retrieve the DWARF version. There was a point in time when the version parameter existed but the DIE parameter did not.

#581 is somewhat related but not the same. That ambiguity was resolved by the version parameter.

**Comment by benediktibk** [comment]
This did the trick, thanks for the answer!
