### ISSUE TITLE
C++ name demangling

### ISSUE THREAD

**Issue by mobiphil** [eliben/pyelftools#66]
Hi, 

so far I know you are interested in the C++ world. Was looking for a python elf reader and bumped into this project. Having seen your blog, had also the hope to find C++ demangling in your library, but unfortunately it is not the case. Are you planning to implement something in this direction or you would just use the libiberty implementation.

Anyway thanks for the great source code.

**Comment by eliben** [comment]
I have no such plans. For mangling/demangling I'd use Clang's C API - I've actually exposed that to Clang's Python bindings at some point.
