### ISSUE TITLE
license mismatch in elftools.construct

### ISSUE THREAD

**Issue by thinred** [eliben/pyelftools#70]
Hello,
I noticed that elftools.construct is a 3rd party library which is, as far as I can tell, under MIT license. This is confusing and quite probably violation of license terms, since the main LICENSE file claims the code to be public domain.

Cheers,
Tomasz

**Comment by eliben** [comment]
As https://github.com/eliben/pyelftools/blob/master/elftools/construct/README says explicitly, `construct` is licensed with its own LICENSE file, which is also included unmodified from the version I forked `construct` from: https://github.com/eliben/pyelftools/blob/master/elftools/construct/LICENSE

**Comment by thinred** [comment]
I understand this very well, however pyelftools are distributed as public-domain, even though clearly some code in the distribution is not public domain. IANAL, but this may be controversial. I understand that you don't claim to put construct under PD, but the fact remains that for all practical purposes it is distributed as such. The users may get a wrong impression that all code is PD. Certainly that was the case for me!
This could be (probably, I'm not sure how it looks legally) solved by explicitly marking in the main LICENSE that the license is PD *and* MIT (for some files). More robust solution is to license pyelftools under MIT, of course. As a plus, the ambiguity of putting a work under PD is avoided.

**Comment by eliben** [comment]
https://github.com/eliben/pyelftools/blob/master/LICENSE explicitly calls out that construct has a license of its own. I don't think there's much else I can/should do here.
