### ISSUE TITLE
Need way to determine raw value of enum

### ISSUE THREAD

**Issue by dcolascione** [eliben/pyelftools#72]
Today, when we decode ELF enum fields, we represent the decoded value as a string. There's no easy way to recover the *numeric* value from which that string was built. Instead of using str directly, we should subclass str and provide an attribute on the subclasses object that contains the original, un-decoded value.

**Comment by eliben** [comment]
[sorry for taking so long to reply]

This information, when needed (which is rare, in my experience) can be obtained from https://github.com/eliben/pyelftools/blob/master/elftools/elf/enums.py

For example, see how it's done here: https://github.com/eliben/pyelftools/blob/master/scripts/readelf.py#L376
