### ISSUE TITLE
Ability to read the full list of ARM build attributes such as Tag_CPU_arch Tag_CPU_name from the .ARM.attributes section

### ISSUE THREAD

**Issue by chr15m** [eliben/pyelftools#75]
There doesn't seem to be a way to access these attributes for ARM ELF binaries.

http://llvm.org/docs/doxygen/html/ARMBuildAttributes_8h_source.html

The readelf tool does the correct thing here:
`readelf -A ...` where ... is some ARM ELF binary will show these tags.

**Comment by chr15m** [comment]
Here is the patch to the 'readelf' command that has the details on how they do this:

http://www.sourceware.org/ml/binutils/2005-09/msg00131.html

**Comment by eliben** [comment]
I suppose you could still use pyelftools to get the raw section from the ELF file; it's just that pyelftools wouldn't decode it for you?

I'd accept a patch/pull request that implements this.

**Comment by chr15m** [comment]
That's what I've done for now, thank you. Will submit a pull request if I get around to patching pyelftools itself. Thanks for the excellent software!

**Comment by sevaa** [comment]
@chr15m is this still an issue?

**Comment by chr15m** [comment]
I no longer work on the software where this was required. Maybe @umlaeute knows.

**Comment by sevaa** [comment]
Well, the ability to parse `.ARM.attributes` has been in the library for a while, so barring a more definitive answer I'd suggest this issue has been fixed...

**Comment by umlaeute** [comment]
i don't fully remember the details, but afaik we have been able to extract all the details we are interested in from ARM binaries for ages (but probably we've just been happy with the manual decoding). it's code that we seldom touch as it  *just works*.

**Comment by sevaa** [comment]
Good to know. Let's close the issue. I can't.
