### ISSUE TITLE
Parsing 12 Mb of DIE's takes 1 minute

### ISSUE THREAD

**Issue by nklacar** [eliben/pyelftools#83]
Hi , 

Performance seems pretty poor when parsing an entire DWARF section for an elf. The DWARF size is about 12 meg and parsing takes 1 minute. 

Attaching perf call graph. Commercial debuggers are able to parse the dwarf in < 2 seconds.  

RepeatUntil parse method seems to be eating most the time. Is it the object copying that is taking too long? 

Any suggestion on how to speed up performance? 

![output2](https://cloud.githubusercontent.com/assets/6211792/9456199/4e608e30-4a89-11e5-8818-5eb9753db46b.png)

**Comment by eliben** [comment]
Performance is a known problem with pyelftools, if you need to read the whole info. The binary parsing library pyelftools is built on (construct) isn't designed for speed :-/

**Comment by nklacar** [comment]
If I was to implement construct in C , would thing speed up? I'm trying to isolate where the biggest bottlenecks are... I like this project since its in python and it would be great if I could make it work for my requirements.

**Comment by eliben** [comment]
Reimplementing construct in C would be a huge undertaking.

I'd invest into more laziness in how pyelftools parses DWARF. You very rarely need ALL OF IT, so it makes sense to parse only the parts you *do* need. pyelftools tries to be lazy, but perhaps more laziness is required.

**Comment by nklacar** [comment]
I need to be able to parse all the variables. Il try and make it only parse the variable names and not the types and use lazy parsing for only the variables I need.

**Comment by eliben** [comment]
There've been several changes to optimize parsing and make it lazier over the past few years. Since this issue is very old I'm going to close it. Feel free to open new issues
